package fix

import (
	"fmt"
	"path/filepath"
	"sort"
	"strings"

	"github.com/vulnetix/cli/v3/internal/cdx"
	"github.com/vulnetix/cli/v3/internal/scan"
	"github.com/vulnetix/cli/v3/pkg/vdb"
)

type Strategy string

const (
	StrategyLatest Strategy = "latest"
	StrategySafest Strategy = "safest"
	StrategyStable Strategy = "stable"
)

type FixMethod string

const (
	MethodDirectBump    FixMethod = "direct-bump"
	MethodOverride      FixMethod = "override"
	MethodParentUpdate  FixMethod = "parent-update"
	MethodParentUpgrade FixMethod = "parent-upgrade"
)

type Options struct {
	Strategy     Strategy
	MaxMajorBump int
	Manifest     string
	Yes          bool
	PathExplicit bool
}

// SafeVersionRejection records why a candidate Safe-Harbour version could not
// be used as an autofix target (vuln count, exploit count, or malware flag).
type SafeVersionRejection struct {
	Version   string
	VulnCount int
	ExplCount int
	IsMalware bool
}

type FixCandidate struct {
	PackageName      string
	Ecosystem        string
	CurrentVer       string
	SourceFile       string
	IsDirect         bool
	ParentName       string
	ParentRange      string
	ParentTarget     string // resolved parent version for a parent-upgrade (npm only)
	TargetVer        string
	Method           FixMethod
	PackageManager   string // concrete resolver (npm/pnpm/yarn/bun/...) for the manifest, when known
	Command          string
	CveIDs           []string
	Reason           string
	Skipped          bool
	SkipReason       string
	RejectedVersions []SafeVersionRejection // populated when SkipReason contains "no Safe-Harbour"
	LatestAvailable  string                 // newest known version for context in the proof-of-work output
}

type FixBatch struct {
	SourceFile string
	Ecosystem  string
	Dir        string
	Plans      []FixCandidate
}

type ProofCounts struct {
	Direct                  int
	TransitiveParentUpdate  int
	TransitiveParentUpgrade int
	TransitiveOverride      int
	UnresolvedDeepChains    int
}

type Batch struct {
	Plans  []FixCandidate
	Counts ProofCounts
}

func BuildPlans(vulns []scan.EnrichedVuln, packages []scan.ScopedPackage, groups []scan.ManifestGroup, insights []vdb.CliPackageInsight, opts Options) Batch {
	insightByPurl := map[string]vdb.CliPackageInsight{}
	for _, ins := range insights {
		if ins.Purl != "" {
			insightByPurl[ins.Purl] = ins
		}
	}
	pkgByKey := map[string]scan.ScopedPackage{}
	pkgByIdentity := map[string]scan.ScopedPackage{}
	for _, p := range packages {
		key := packageKey(p.Name, p.Version, p.Ecosystem, p.SourceFile)
		if _, exists := pkgByKey[key]; !exists {
			pkgByKey[key] = p
		}
		identity := identityKey(p.Name, p.Version, p.Ecosystem)
		if _, exists := pkgByIdentity[identity]; !exists {
			pkgByIdentity[identity] = p
		}
	}

	byFinding := map[string]*FixCandidate{}
	legacyFixVersions := map[string][]string{}
	for _, v := range vulns {
		p := pkgByKey[packageKey(v.PackageName, v.PackageVer, v.Ecosystem, v.SourceFile)]
		if p.Name == "" {
			p = pkgByIdentity[identityKey(v.PackageName, v.PackageVer, v.Ecosystem)]
		}
		if p.Name == "" {
			p = scan.ScopedPackage{
				Name:       v.PackageName,
				Version:    v.PackageVer,
				Ecosystem:  v.Ecosystem,
				SourceFile: v.SourceFile,
				IsDirect:   true,
			}
		}
		// Fixes are applied to the manifest, never a lockfile: a lockfile entry
		// is regenerated by the install step. Normalising the source to the
		// sibling manifest also collapses the duplicate (manifest + lockfile)
		// candidates the scanner reports for the same dependency.
		editFile := editableManifestFor(p.SourceFile, groups)
		if opts.Manifest != "" && !sameManifest(opts.Manifest, editFile) {
			continue
		}
		key := packagePlanKey(v.Ecosystem, v.PackageName, editFile)
		fc := byFinding[key]
		if fc == nil {
			fc = &FixCandidate{
				PackageName: p.Name,
				Ecosystem:   p.Ecosystem,
				CurrentVer:  nonEmpty(p.Version, v.PackageVer),
				SourceFile:  editFile,
				IsDirect:    isDirectPackage(p, groups),
			}
			byFinding[key] = fc
		}
		fc.CveIDs = appendUnique(fc.CveIDs, v.CveID)
		if v.Remediation != nil && v.Remediation.FixVersion != "" {
			legacyFixVersions[key] = appendUnique(legacyFixVersions[key], v.Remediation.FixVersion)
		}
	}

	out := make([]FixCandidate, 0, len(byFinding))
	var counts ProofCounts
	for _, fc := range byFinding {
		purl := cdx.BuildLocalPurl(fc.PackageName, fc.CurrentVer, fc.Ecosystem)
		ins := insightByPurl[purl]
		target, decision := ResolveTarget(fc.CurrentVer, opts.Strategy, ins.LatestVersions, ins.SafeVersions, ins.SafeHarbour, opts.MaxMajorBump)
		if decision.Skipped && strings.Contains(decision.Reason, "no Safe-Harbour") {
			if fallback, fallbackDecision := remediationFallbackTarget(fc.CurrentVer, legacyFixVersions[packagePlanKey(fc.Ecosystem, fc.PackageName, fc.SourceFile)], opts.MaxMajorBump); fallback != "" {
				target = fallback
				decision = fallbackDecision
				fc.Reason = "using legacy remediation fix version because Safe-Harbour data was unavailable"
			} else {
				// Record why every candidate was rejected so the proof-of-work
				// output can explain which options were considered.
				for _, sv := range ins.SafeVersions {
					if sv.Version == "" {
						continue
					}
					if !isUsableSafeVersion(sv) {
						fc.RejectedVersions = append(fc.RejectedVersions, SafeVersionRejection{
							Version:   sv.Version,
							VulnCount: sv.VulnerabilityCount,
							ExplCount: sv.ExploitCount,
							IsMalware: sv.IsMalware,
						})
					}
				}
				if len(ins.LatestVersions) > 0 {
					fc.LatestAvailable = ins.LatestVersions[0].Version
				}
			}
		}
		if decision.Skipped {
			fc.Skipped = true
			fc.SkipReason = decision.Reason
		} else {
			fc.TargetVer = target
		}

		if fc.IsDirect {
			fc.Method = MethodDirectBump
			if fc.TargetVer == "" {
				fc.Command = commandFor(*fc, "")
			} else {
				fc.Command = commandFor(*fc, fc.TargetVer)
			}
			if !fc.Skipped {
				counts.Direct++
			}
			out = append(out, *fc)
			continue
		}

		// Prefer the server-resolved cross-ecosystem parent-upgrade when present
		// (replaces the old direct npm-registry probe); otherwise resolve a
		// deterministic parent-update / override locally.
		if !applyTransitiveRecommendation(fc, ins.TransitiveFix) {
			resolveTransitive(fc, groups)
		}
		if fc.Command == "" {
			fc.Command = commandFor(*fc, fc.TargetVer)
		}
		if fc.Skipped {
			counts.UnresolvedDeepChains++
		} else {
			switch fc.Method {
			case MethodParentUpdate:
				counts.TransitiveParentUpdate++
			case MethodParentUpgrade:
				counts.TransitiveParentUpgrade++
			case MethodOverride:
				counts.TransitiveOverride++
			default:
				counts.UnresolvedDeepChains++
			}
		}
		out = append(out, *fc)
	}

	reconcileParentUpgrades(out)

	sort.Slice(out, func(i, j int) bool {
		if out[i].SourceFile != out[j].SourceFile {
			return out[i].SourceFile < out[j].SourceFile
		}
		return out[i].PackageName < out[j].PackageName
	})
	return Batch{Plans: out, Counts: counts}
}

// applyTransitiveRecommendation applies a server-resolved parent-upgrade to the
// candidate. The vdb-api resolves "which parent version admits the safe child"
// cross-ecosystem (via the shared registry module), so the CLI no longer probes a
// registry itself. Returns true when a concrete parent-upgrade was applied;
// otherwise the caller resolves a deterministic parent-update / override locally.
func applyTransitiveRecommendation(fc *FixCandidate, rec *vdb.CliTransitiveFix) bool {
	if rec == nil || rec.Method != "parent-upgrade" || rec.ParentName == "" || rec.ParentTarget == "" {
		return false
	}
	fc.Method = MethodParentUpgrade
	fc.ParentName = rec.ParentName
	fc.ParentTarget = rec.ParentTarget
	if rec.ChildTarget != "" {
		fc.TargetVer = rec.ChildTarget
	}
	fc.Skipped = false
	if rec.Reason != "" {
		fc.Reason = rec.Reason
	}
	fc.Command = commandFor(*fc, fc.TargetVer)
	return true
}

// parentReconcileKey identifies a dependency within a manifest for matching a
// parent-upgrade's parent against a direct bump of the same package.
func parentReconcileKey(ecosystem, name, sourceFile string) string {
	return strings.ToLower(ecosystem) + "\x00" + strings.ToLower(name) + "\x00" + sourceFile
}

// reconcileParentUpgrades raises a parent-upgrade target to the higher of itself
// and a direct bump of the SAME parent in the same manifest. When a parent is
// itself vulnerable and being bumped (e.g. to the latest safe version), a
// transitive parent-upgrade that only raised it just enough to admit the safe
// child would undershoot — and, applied together, the two edits conflict. Taking
// the higher version makes the parent end safe AND still admit the safe child.
func reconcileParentUpgrades(out []FixCandidate) {
	directTargets := map[string]string{}
	for _, c := range out {
		if c.Method == MethodDirectBump && !c.Skipped && c.TargetVer != "" {
			directTargets[parentReconcileKey(c.Ecosystem, c.PackageName, c.SourceFile)] = c.TargetVer
		}
	}
	for i := range out {
		if out[i].Method != MethodParentUpgrade || out[i].ParentName == "" {
			continue
		}
		dt, ok := directTargets[parentReconcileKey(out[i].Ecosystem, out[i].ParentName, out[i].SourceFile)]
		if ok && dt != "" && (out[i].ParentTarget == "" || greaterOrEqual(dt, out[i].ParentTarget)) {
			out[i].ParentTarget = dt
			out[i].Command = commandFor(out[i], out[i].TargetVer)
		}
	}
}

func GroupBatches(root string, plans []FixCandidate) []FixBatch {
	grouped := map[string]*FixBatch{}
	for _, p := range plans {
		key := p.SourceFile + "::" + p.Ecosystem
		b := grouped[key]
		if b == nil {
			b = &FixBatch{
				SourceFile: p.SourceFile,
				Ecosystem:  p.Ecosystem,
				Dir:        filepath.Dir(filepath.Join(root, p.SourceFile)),
			}
			grouped[key] = b
		}
		b.Plans = append(b.Plans, p)
	}
	out := make([]FixBatch, 0, len(grouped))
	for _, b := range grouped {
		out = append(out, *b)
	}
	sort.Slice(out, func(i, j int) bool { return out[i].SourceFile < out[j].SourceFile })
	return out
}

func CountPlans(plans []FixCandidate) ProofCounts {
	var counts ProofCounts
	for _, p := range plans {
		if p.Skipped {
			if !p.IsDirect {
				counts.UnresolvedDeepChains++
			}
			continue
		}
		if p.IsDirect {
			counts.Direct++
			continue
		}
		switch p.Method {
		case MethodParentUpdate:
			counts.TransitiveParentUpdate++
		case MethodParentUpgrade:
			counts.TransitiveParentUpgrade++
		case MethodOverride:
			counts.TransitiveOverride++
		default:
			counts.UnresolvedDeepChains++
		}
	}
	return counts
}

func ValidateStrategy(s string) (Strategy, error) {
	switch Strategy(strings.ToLower(strings.TrimSpace(s))) {
	case StrategyLatest:
		return StrategyLatest, nil
	case StrategySafest:
		return StrategySafest, nil
	case "", StrategyStable:
		return StrategyStable, nil
	default:
		return "", fmt.Errorf("invalid --sca-autofix-strategy %q: must be latest, safest, or stable", s)
	}
}

func packageKey(name, version, ecosystem, source string) string {
	return strings.ToLower(ecosystem) + "::" + strings.ToLower(name) + "::" + version + "::" + source
}

func identityKey(name, version, ecosystem string) string {
	return strings.ToLower(ecosystem) + "::" + strings.ToLower(name) + "::" + version
}

func packagePlanKey(ecosystem, name, source string) string {
	return strings.ToLower(ecosystem) + "::" + strings.ToLower(name) + "::" + source
}

func remediationFallbackTarget(current string, versions []string, maxMajorBump int) (string, TargetDecision) {
	if len(versions) == 0 {
		return "", TargetDecision{Skipped: true, Reason: "no remediation fix version available"}
	}
	current = normalizeVersion(current)
	candidates := make([]string, 0, len(versions))
	seen := map[string]bool{}
	for _, v := range versions {
		v = normalizeVersion(v)
		if v == "" || seen[v] {
			continue
		}
		seen[v] = true
		if current != "" && (v == current || lessThan(v, current)) {
			continue
		}
		if maxMajorBump >= 0 && current != "" {
			curMajor, okCur := majorOf(current)
			tgtMajor, okTarget := majorOf(v)
			if okCur && okTarget && int(tgtMajor-curMajor) > maxMajorBump {
				continue
			}
		}
		candidates = append(candidates, v)
	}
	sorted := sortableVersions(candidates, true)
	if len(sorted) == 0 {
		return "", TargetDecision{Skipped: true, Reason: "remediation fix version was unavailable within autofix guardrails"}
	}
	return sorted[0], TargetDecision{}
}

func sameManifest(want, got string) bool {
	if want == got {
		return true
	}
	return filepath.Clean(want) == filepath.Clean(got) || filepath.Base(want) == filepath.Base(got)
}

func nonEmpty(a, b string) string {
	if a != "" {
		return a
	}
	return b
}

func appendUnique(in []string, s string) []string {
	if s == "" {
		return in
	}
	for _, v := range in {
		if v == s {
			return in
		}
	}
	return append(in, s)
}

// editableManifestFor maps a finding's source file to the manifest that should
// be edited. If the source is a lockfile, it returns the sibling manifest in the
// same directory (e.g. package-lock.json → package.json); otherwise it returns
// the source unchanged.
func editableManifestFor(sourceFile string, groups []scan.ManifestGroup) string {
	if !isLockfile(sourceFile) {
		return sourceFile
	}
	dir := filepath.Dir(sourceFile)
	for _, g := range groups {
		for _, f := range g.Files {
			if filepath.Dir(f) == dir && !isLockfile(f) {
				return f
			}
		}
	}
	return sourceFile
}

func isLockfile(sourceFile string) bool {
	if info, ok := scan.DetectManifest(filepath.Base(sourceFile)); ok {
		return info.IsLock
	}
	return false
}

func isDirectPackage(p scan.ScopedPackage, groups []scan.ManifestGroup) bool {
	if p.IsDirect {
		return true
	}
	for _, g := range groups {
		if g.Graph == nil {
			continue
		}
		for _, f := range g.Files {
			if f == p.SourceFile {
				return g.Graph.IsDirect(p.Name)
			}
		}
	}
	return p.IsDirect
}
