package fix

import (
	"fmt"
	"path/filepath"
	"sort"
	"strings"

	"github.com/vulnetix/cli/v3/internal/cdx"
	"github.com/vulnetix/cli/v3/internal/scan"
	"github.com/vulnetix/cli/v3/pkg/vdb"
)

type Strategy string

const (
	StrategyLatest Strategy = "latest"
	StrategySafest Strategy = "safest"
	StrategyStable Strategy = "stable"
)

type FixMethod string

const (
	MethodDirectBump    FixMethod = "direct-bump"
	MethodOverride      FixMethod = "override"
	MethodParentUpdate  FixMethod = "parent-update"
	MethodParentUpgrade FixMethod = "parent-upgrade"
)

type Options struct {
	Strategy     Strategy
	MaxMajorBump int
	Manifest     string
	Yes          bool
	PathExplicit bool
}

type FixCandidate struct {
	PackageName    string
	Ecosystem      string
	CurrentVer     string
	SourceFile     string
	IsDirect       bool
	ParentName     string
	ParentRange    string
	ParentTarget   string // resolved parent version for a parent-upgrade (npm only)
	TargetVer      string
	Method         FixMethod
	PackageManager string // concrete resolver (npm/pnpm/yarn/bun/...) for the manifest, when known
	Command        string
	CveIDs         []string
	Reason         string
	Skipped        bool
	SkipReason     string
}

type FixBatch struct {
	SourceFile string
	Ecosystem  string
	Dir        string
	Plans      []FixCandidate
}

type ProofCounts struct {
	Direct                  int
	TransitiveParentUpdate  int
	TransitiveParentUpgrade int
	TransitiveOverride      int
	UnresolvedDeepChains    int
}

type Batch struct {
	Plans  []FixCandidate
	Counts ProofCounts
}

func BuildPlans(vulns []scan.EnrichedVuln, packages []scan.ScopedPackage, groups []scan.ManifestGroup, insights []vdb.CliPackageInsight, opts Options) Batch {
	insightByPurl := map[string]vdb.CliPackageInsight{}
	for _, ins := range insights {
		if ins.Purl != "" {
			insightByPurl[ins.Purl] = ins
		}
	}
	pkgByKey := map[string]scan.ScopedPackage{}
	pkgByIdentity := map[string]scan.ScopedPackage{}
	for _, p := range packages {
		key := packageKey(p.Name, p.Version, p.Ecosystem, p.SourceFile)
		if _, exists := pkgByKey[key]; !exists {
			pkgByKey[key] = p
		}
		identity := identityKey(p.Name, p.Version, p.Ecosystem)
		if _, exists := pkgByIdentity[identity]; !exists {
			pkgByIdentity[identity] = p
		}
	}

	byFinding := map[string]*FixCandidate{}
	for _, v := range vulns {
		p := pkgByKey[packageKey(v.PackageName, v.PackageVer, v.Ecosystem, v.SourceFile)]
		if p.Name == "" {
			p = pkgByIdentity[identityKey(v.PackageName, v.PackageVer, v.Ecosystem)]
		}
		if p.Name == "" {
			p = scan.ScopedPackage{
				Name:       v.PackageName,
				Version:    v.PackageVer,
				Ecosystem:  v.Ecosystem,
				SourceFile: v.SourceFile,
				IsDirect:   true,
			}
		}
		// Fixes are applied to the manifest, never a lockfile: a lockfile entry
		// is regenerated by the install step. Normalising the source to the
		// sibling manifest also collapses the duplicate (manifest + lockfile)
		// candidates the scanner reports for the same dependency.
		editFile := editableManifestFor(p.SourceFile, groups)
		if opts.Manifest != "" && !sameManifest(opts.Manifest, editFile) {
			continue
		}
		key := strings.ToLower(v.Ecosystem) + "::" + strings.ToLower(v.PackageName) + "::" + editFile
		fc := byFinding[key]
		if fc == nil {
			fc = &FixCandidate{
				PackageName: p.Name,
				Ecosystem:   p.Ecosystem,
				CurrentVer:  nonEmpty(p.Version, v.PackageVer),
				SourceFile:  editFile,
				IsDirect:    isDirectPackage(p, groups),
			}
			byFinding[key] = fc
		}
		fc.CveIDs = appendUnique(fc.CveIDs, v.CveID)
	}

	out := make([]FixCandidate, 0, len(byFinding))
	var counts ProofCounts
	for _, fc := range byFinding {
		purl := cdx.BuildLocalPurl(fc.PackageName, fc.CurrentVer, fc.Ecosystem)
		ins := insightByPurl[purl]
		target, decision := ResolveTarget(fc.CurrentVer, opts.Strategy, ins.LatestVersions, ins.SafeVersions, ins.SafeHarbour, opts.MaxMajorBump)
		if decision.Skipped {
			fc.Skipped = true
			fc.SkipReason = decision.Reason
		} else {
			fc.TargetVer = target
		}

		if fc.IsDirect {
			fc.Method = MethodDirectBump
			if fc.TargetVer == "" {
				fc.Command = commandFor(*fc, "")
			} else {
				fc.Command = commandFor(*fc, fc.TargetVer)
			}
			if !fc.Skipped {
				counts.Direct++
			}
			out = append(out, *fc)
			continue
		}

		resolveTransitive(fc, groups, packages)
		if fc.Command == "" {
			fc.Command = commandFor(*fc, fc.TargetVer)
		}
		if fc.Skipped {
			counts.UnresolvedDeepChains++
		} else {
			switch fc.Method {
			case MethodParentUpdate:
				counts.TransitiveParentUpdate++
			case MethodParentUpgrade:
				counts.TransitiveParentUpgrade++
			case MethodOverride:
				counts.TransitiveOverride++
			default:
				counts.UnresolvedDeepChains++
			}
		}
		out = append(out, *fc)
	}

	sort.Slice(out, func(i, j int) bool {
		if out[i].SourceFile != out[j].SourceFile {
			return out[i].SourceFile < out[j].SourceFile
		}
		return out[i].PackageName < out[j].PackageName
	})
	return Batch{Plans: out, Counts: counts}
}

func GroupBatches(root string, plans []FixCandidate) []FixBatch {
	grouped := map[string]*FixBatch{}
	for _, p := range plans {
		key := p.SourceFile + "::" + p.Ecosystem
		b := grouped[key]
		if b == nil {
			b = &FixBatch{
				SourceFile: p.SourceFile,
				Ecosystem:  p.Ecosystem,
				Dir:        filepath.Dir(filepath.Join(root, p.SourceFile)),
			}
			grouped[key] = b
		}
		b.Plans = append(b.Plans, p)
	}
	out := make([]FixBatch, 0, len(grouped))
	for _, b := range grouped {
		out = append(out, *b)
	}
	sort.Slice(out, func(i, j int) bool { return out[i].SourceFile < out[j].SourceFile })
	return out
}

func CountPlans(plans []FixCandidate) ProofCounts {
	var counts ProofCounts
	for _, p := range plans {
		if p.Skipped {
			if !p.IsDirect {
				counts.UnresolvedDeepChains++
			}
			continue
		}
		if p.IsDirect {
			counts.Direct++
			continue
		}
		switch p.Method {
		case MethodParentUpdate:
			counts.TransitiveParentUpdate++
		case MethodParentUpgrade:
			counts.TransitiveParentUpgrade++
		case MethodOverride:
			counts.TransitiveOverride++
		default:
			counts.UnresolvedDeepChains++
		}
	}
	return counts
}

func ValidateStrategy(s string) (Strategy, error) {
	switch Strategy(strings.ToLower(strings.TrimSpace(s))) {
	case StrategyLatest:
		return StrategyLatest, nil
	case StrategySafest:
		return StrategySafest, nil
	case "", StrategyStable:
		return StrategyStable, nil
	default:
		return "", fmt.Errorf("invalid --sca-autofix-strategy %q: must be latest, safest, or stable", s)
	}
}

func packageKey(name, version, ecosystem, source string) string {
	return strings.ToLower(ecosystem) + "::" + strings.ToLower(name) + "::" + version + "::" + source
}

func identityKey(name, version, ecosystem string) string {
	return strings.ToLower(ecosystem) + "::" + strings.ToLower(name) + "::" + version
}

func sameManifest(want, got string) bool {
	if want == got {
		return true
	}
	return filepath.Clean(want) == filepath.Clean(got) || filepath.Base(want) == filepath.Base(got)
}

func nonEmpty(a, b string) string {
	if a != "" {
		return a
	}
	return b
}

func appendUnique(in []string, s string) []string {
	if s == "" {
		return in
	}
	for _, v := range in {
		if v == s {
			return in
		}
	}
	return append(in, s)
}

// editableManifestFor maps a finding's source file to the manifest that should
// be edited. If the source is a lockfile, it returns the sibling manifest in the
// same directory (e.g. package-lock.json → package.json); otherwise it returns
// the source unchanged.
func editableManifestFor(sourceFile string, groups []scan.ManifestGroup) string {
	if !isLockfile(sourceFile) {
		return sourceFile
	}
	dir := filepath.Dir(sourceFile)
	for _, g := range groups {
		for _, f := range g.Files {
			if filepath.Dir(f) == dir && !isLockfile(f) {
				return f
			}
		}
	}
	return sourceFile
}

func isLockfile(sourceFile string) bool {
	if info, ok := scan.DetectManifest(filepath.Base(sourceFile)); ok {
		return info.IsLock
	}
	return false
}

func isDirectPackage(p scan.ScopedPackage, groups []scan.ManifestGroup) bool {
	if p.IsDirect {
		return true
	}
	for _, g := range groups {
		if g.Graph == nil {
			continue
		}
		for _, f := range g.Files {
			if f == p.SourceFile {
				return g.Graph.IsDirect(p.Name)
			}
		}
	}
	return p.IsDirect
}
