package vulnetix.rules.vnx_sec_461

import rego.v1
import data.vulnetix.lib.secrets

# GENERATED by internal/sast/secretsgen from catalog.json — do not edit by hand.

metadata := {
	"id": "VNX-SEC-461",
	"name": "Knock public API key (pk_)",
	"description": "A Knock publishable API key (pk_ / pk_test_) was found near a knock assignment. Public keys identify the Knock environment for client SDKs.",
	"help_uri": "https://docs.cli.vulnetix.com/docs/sast-rules/secrets/communication/#vnx-sec-461",
	"languages": [],
	"severity": "low",
	"level": "note",
	"kind": "secrets",
	"cwe": [798],
	"capec": ["CAPEC-191"],
	"attack_technique": ["T1552.001"],
	"cvssv4": "",
	"cwss": "CWSS:1.0/TI:L/AP:A/AL:L/IC:L/FC:L/RP:H/RL:H/AV:N/AS:L/IN:L/SC:N/CONF:N/T:A/P:L",
	"tags": ["secrets", "knock", "communication"],
}

_pattern := `(?i)knock[a-z0-9_]*(?:public[_-]?key|publishable[_-]?key|pk)[a-z0-9_]*\s*[:=]\s*['"]?(pk_(?:test_)?[A-Za-z0-9_-]{20,50})['"]?`
_keywords := ["knock", "pk_"]

findings contains finding if {
	some path in object.keys(input.file_contents)
	not secrets.skip_path(path)
	lines := split(input.file_contents[path], "\n")
	some i, line in lines
	secrets.has_keyword(line, _keywords)
	m := regex.find_all_string_submatch_n(_pattern, line, 1)
	count(m) > 0
	token := m[0][1]
	not secrets.is_example_token(token)
	secrets.high_entropy(token, 3)
	finding := {
		"rule_id": metadata.id,
		"message": "Knock public API key found; client-safe, but confirm the paired secret key was not committed",
		"artifact_uri": path,
		"severity": metadata.severity,
		"level": metadata.level,
		"start_line": i + 1,
		"snippet": secrets.redact(line),
	}
}
