package vulnetix.rules.vnx_sec_236

import rego.v1
import data.vulnetix.lib.secrets

# GENERATED by internal/sast/secretsgen from catalog.json — do not edit by hand.

metadata := {
	"id": "VNX-SEC-236",
	"name": "Spacelift API key secret",
	"description": "A Spacelift API key secret paired with an API key ID was found. Together they exchange for a Spacelift API JWT granting IaC management access.",
	"help_uri": "https://docs.cli.vulnetix.com/docs/sast-rules/secrets/source-control/#vnx-sec-236",
	"languages": [],
	"severity": "high",
	"level": "error",
	"kind": "secrets",
	"cwe": [798],
	"capec": ["CAPEC-191"],
	"attack_technique": ["T1552.001"],
	"cvssv4": "",
	"cwss": "CWSS:1.0/TI:H/AP:A/AL:M/IC:H/FC:H/RP:H/RL:H/AV:N/AS:L/IN:L/SC:N/CONF:N/T:A/P:M",
	"tags": ["secrets", "spacelift", "source-control"],
}

_pattern := `(?i)spacelift[a-z0-9_]*(?:api[_-]?key[_-]?secret|secret)\s*[:=]\s*['"]?([A-Za-z0-9]{40,})['"]?`
_keywords := ["spacelift", "secret"]

findings contains finding if {
	some path in object.keys(input.file_contents)
	not secrets.skip_path(path)
	lines := split(input.file_contents[path], "\n")
	some i, line in lines
	secrets.has_keyword(line, _keywords)
	m := regex.find_all_string_submatch_n(_pattern, line, 1)
	count(m) > 0
	token := m[0][1]
	not secrets.is_example_token(token)
	secrets.high_entropy(token, 3.6)
	finding := {
		"rule_id": metadata.id,
		"message": "Spacelift API key secret found; rotate the API key in Spacelift settings",
		"artifact_uri": path,
		"severity": metadata.severity,
		"level": metadata.level,
		"start_line": i + 1,
		"snippet": secrets.redact(line),
	}
}
