package vulnetix.rules.vnx_sec_472

import rego.v1
import data.vulnetix.lib.secrets

# GENERATED by internal/sast/secretsgen from catalog.json — do not edit by hand.

metadata := {
	"id": "VNX-SEC-472",
	"name": "ClickSend username+API key Basic header",
	"description": "A ClickSend Basic Auth credential (username:apikey) was found in an authorization header. It grants access to ClickSend SMS, voice, and account APIs.",
	"help_uri": "https://docs.cli.vulnetix.com/docs/sast-rules/secrets/communication/#vnx-sec-472",
	"languages": [],
	"severity": "high",
	"level": "error",
	"kind": "secrets",
	"cwe": [798],
	"capec": ["CAPEC-191"],
	"attack_technique": ["T1552.001"],
	"cvssv4": "",
	"cwss": "CWSS:1.0/TI:H/AP:A/AL:M/IC:H/FC:H/RP:H/RL:H/AV:N/AS:L/IN:L/SC:N/CONF:N/T:A/P:M",
	"tags": ["secrets", "clicksend", "communication"],
}

_pattern := `(?i)clicksend[a-z0-9_]*(?:basic|authorization|auth)[a-z0-9_]*\s*[:=]\s*['"]?(?:Basic\s+)?([A-Za-z0-9+/]{40,}={0,2})['"]?`
_keywords := ["clicksend"]

findings contains finding if {
	some path in object.keys(input.file_contents)
	not secrets.skip_path(path)
	lines := split(input.file_contents[path], "\n")
	some i, line in lines
	secrets.has_keyword(line, _keywords)
	m := regex.find_all_string_submatch_n(_pattern, line, 1)
	count(m) > 0
	token := m[0][1]
	not secrets.is_example_token(token)
	secrets.high_entropy(token, 4)
	finding := {
		"rule_id": metadata.id,
		"message": "ClickSend Basic auth credential found; rotate the API key in the ClickSend dashboard under Account \u003e API Credentials",
		"artifact_uri": path,
		"severity": metadata.severity,
		"level": metadata.level,
		"start_line": i + 1,
		"snippet": secrets.redact(line),
	}
}
