package vulnetix.rules.vnx_sec_1008

import rego.v1
import data.vulnetix.lib.secrets

# GENERATED by internal/sast/secretsgen from catalog.json — do not edit by hand.

metadata := {
	"id": "VNX-SEC-1008",
	"name": "TRM Labs API key (assignment)",
	"description": "A TRM Labs API key assigned to a trm field was found. It authenticates blockchain-intelligence and wallet-screening requests against the TRM Labs API.",
	"help_uri": "https://docs.cli.vulnetix.com/docs/sast-rules/secrets/crypto-blockchain/#vnx-sec-1008",
	"languages": [],
	"severity": "high",
	"level": "error",
	"kind": "secrets",
	"cwe": [798],
	"capec": ["CAPEC-191"],
	"attack_technique": ["T1552.001"],
	"cvssv4": "",
	"cwss": "CWSS:1.0/TI:H/AP:A/AL:M/IC:H/FC:H/RP:H/RL:H/AV:N/AS:L/IN:L/SC:N/CONF:N/T:A/P:M",
	"tags": ["secrets", "trmlabs", "crypto-blockchain"],
}

_pattern := `(?i)trm(?:[_-]?labs)?[a-z0-9_]*(?:api[_-]?key|key|token)\s*[:=]\s*['"]?([A-Za-z0-9_-]{32,48})['"]?`
_keywords := ["trm", "key"]

findings contains finding if {
	some path in object.keys(input.file_contents)
	not secrets.skip_path(path)
	lines := split(input.file_contents[path], "\n")
	some i, line in lines
	secrets.has_keyword(line, _keywords)
	m := regex.find_all_string_submatch_n(_pattern, line, 1)
	count(m) > 0
	token := m[0][1]
	not secrets.is_example_token(token)
	secrets.high_entropy(token, 4)
	finding := {
		"rule_id": metadata.id,
		"message": "TRM Labs API key found; rotate it in the TRM Labs dashboard",
		"artifact_uri": path,
		"severity": metadata.severity,
		"level": metadata.level,
		"start_line": i + 1,
		"snippet": secrets.redact(line),
	}
}
