package vulnetix.rules.vnx_sec_591

import rego.v1
import data.vulnetix.lib.secrets

# GENERATED by internal/sast/secretsgen from catalog.json — do not edit by hand.

metadata := {
	"id": "VNX-SEC-591",
	"name": "TimescaleDB Cloud connection string",
	"description": "A Postgres connection string embedding a password against a Timescale Cloud (tsdb.cloud.timescale.com) host was found. It grants authenticated access to the managed TimescaleDB instance.",
	"help_uri": "https://docs.cli.vulnetix.com/docs/sast-rules/secrets/database/#vnx-sec-591",
	"languages": [],
	"severity": "critical",
	"level": "error",
	"kind": "secrets",
	"cwe": [798],
	"capec": ["CAPEC-191"],
	"attack_technique": ["T1552.001"],
	"cvssv4": "",
	"cwss": "CWSS:1.0/TI:H/AP:A/AL:H/IC:H/FC:H/RP:H/RL:H/AV:N/AS:L/IN:L/SC:N/CONF:N/T:A/P:H",
	"tags": ["secrets", "timescaledb", "database"],
}

_pattern := `postgres(?:ql)?:\/\/[A-Za-z0-9_.-]+:([^@\s'"]{8,})@[A-Za-z0-9_.-]*\.timescale\.com`
_keywords := [".timescale.com"]

findings contains finding if {
	some path in object.keys(input.file_contents)
	not secrets.skip_path(path)
	lines := split(input.file_contents[path], "\n")
	some i, line in lines
	secrets.has_keyword(line, _keywords)
	m := regex.find_all_string_submatch_n(_pattern, line, 1)
	count(m) > 0
	token := m[0][1]
	not secrets.is_example_token(token)
	finding := {
		"rule_id": metadata.id,
		"message": "TimescaleDB Cloud connection password found; reset the service password in the Timescale console and rotate the connection string",
		"artifact_uri": path,
		"severity": metadata.severity,
		"level": metadata.level,
		"start_line": i + 1,
		"snippet": secrets.redact(line),
	}
}
