package vulnetix.rules.vnx_sec_392

import rego.v1
import data.vulnetix.lib.secrets

# GENERATED by internal/sast/secretsgen from catalog.json — do not edit by hand.

metadata := {
	"id": "VNX-SEC-392",
	"name": "Adyen merchant account + key combo (live URL prefix key)",
	"description": "An Adyen live-prefix API key URL token (AdyenLivePrefix style) was found near an adyen live endpoint assignment. It identifies the live API endpoint binding for the merchant.",
	"help_uri": "https://docs.cli.vulnetix.com/docs/sast-rules/secrets/payment/#vnx-sec-392",
	"languages": [],
	"severity": "medium",
	"level": "warning",
	"kind": "secrets",
	"cwe": [798],
	"capec": ["CAPEC-191"],
	"attack_technique": ["T1552.001"],
	"cvssv4": "",
	"cwss": "CWSS:1.0/TI:M/AP:A/AL:M/IC:M/FC:M/RP:H/RL:H/AV:N/AS:L/IN:L/SC:N/CONF:N/T:A/P:M",
	"tags": ["secrets", "adyen", "payment"],
}

_pattern := `(?i)adyen[a-z0-9_]*(?:live[_-]?prefix|prefix)[a-z0-9_]*\s*[:=]\s*['"]?([0-9a-f]{32,})['"]?`
_keywords := ["adyen", "prefix"]

findings contains finding if {
	some path in object.keys(input.file_contents)
	not secrets.skip_path(path)
	lines := split(input.file_contents[path], "\n")
	some i, line in lines
	secrets.has_keyword(line, _keywords)
	m := regex.find_all_string_submatch_n(_pattern, line, 1)
	count(m) > 0
	token := m[0][1]
	not secrets.is_example_token(token)
	secrets.high_entropy(token, 3.5)
	finding := {
		"rule_id": metadata.id,
		"message": "Adyen live URL prefix found; not a secret alone, but confirm the paired API key and HMAC were not committed",
		"artifact_uri": path,
		"severity": metadata.severity,
		"level": metadata.level,
		"start_line": i + 1,
		"snippet": secrets.redact(line),
	}
}
