package vulnetix.rules.vnx_sec_623

import rego.v1
import data.vulnetix.lib.secrets

# GENERATED by internal/sast/secretsgen from catalog.json — do not edit by hand.

metadata := {
	"id": "VNX-SEC-623",
	"name": "Prometheus remote-write basic-auth URL",
	"description": "A Prometheus remote-write or remote-read URL embedding HTTP basic-auth credentials was found. The embedded password authenticates pushes to the remote-write endpoint (e.g. Mimir, Thanos, Grafana Cloud).",
	"help_uri": "https://docs.cli.vulnetix.com/docs/sast-rules/secrets/monitoring/#vnx-sec-623",
	"languages": [],
	"severity": "high",
	"level": "error",
	"kind": "secrets",
	"cwe": [798],
	"capec": ["CAPEC-191"],
	"attack_technique": ["T1552.001"],
	"cvssv4": "",
	"cwss": "CWSS:1.0/TI:H/AP:A/AL:M/IC:H/FC:H/RP:H/RL:H/AV:N/AS:L/IN:L/SC:N/CONF:N/T:A/P:M",
	"tags": ["secrets", "prometheus", "monitoring"],
}

_pattern := `(?i)https?:\/\/[0-9]+:([^@\s'"]{8,})@[A-Za-z0-9_.:-]+\/api\/(?:prom\/push|v1\/(?:write|push))`
_keywords := ["/api/prom/push", "/api/v1/write"]

findings contains finding if {
	some path in object.keys(input.file_contents)
	not secrets.skip_path(path)
	lines := split(input.file_contents[path], "\n")
	some i, line in lines
	secrets.has_keyword(line, _keywords)
	m := regex.find_all_string_submatch_n(_pattern, line, 1)
	count(m) > 0
	token := m[0][1]
	not secrets.is_example_token(token)
	finding := {
		"rule_id": metadata.id,
		"message": "Prometheus remote-write credential found; rotate the remote-write password/token at the backend and move it to a basic_auth password_file or secret",
		"artifact_uri": path,
		"severity": metadata.severity,
		"level": metadata.level,
		"start_line": i + 1,
		"snippet": secrets.redact(line),
	}
}
