package vulnetix.rules.vnx_node_020

import rego.v1

metadata := {
	"id": "VNX-NODE-020",
	"name": "Deprecated crypto.createCipher/createDecipher without IV",
	"description": "crypto.createCipher() and crypto.createDecipher() are deprecated because they derive the IV deterministically from the key and password, producing the same IV on every call. For stream and counter modes (CTR, GCM, CCM) this completely breaks confidentiality and integrity. Use crypto.createCipheriv() and crypto.createDecipheriv() with a random IV generated by crypto.randomBytes().",
	"help_uri": "https://docs.cli.vulnetix.com/docs/sast-rules/vnx-node-020/",
	"languages": ["javascript", "typescript"],
	"severity": "high",
	"level": "error",
	"kind": "sast",
	"cwe": [330],
	"capec": ["CAPEC-20"],
	"attack_technique": ["T1600"],
	"cvssv4": "",
	"cwss": "CWSS:1.0/TI:H/AP:A/AL:H/IC:H/FC:H/RP:H/RL:H/AV:N/AS:L/IN:L/SC:N/CONF:N/T:A/P:H",
	"tags": ["crypto", "weak-iv", "encryption", "node"],
}

_is_js(path) if endswith(path, ".js")
_is_js(path) if endswith(path, ".ts")
_is_js(path) if endswith(path, ".jsx")
_is_js(path) if endswith(path, ".tsx")
_is_js(path) if endswith(path, ".mjs")
_is_js(path) if endswith(path, ".cjs")

findings contains finding if {
	some path in object.keys(input.file_contents)
	_is_js(path)
	not endswith(path, ".min.js")
	lines := split(input.file_contents[path], "\n")
	some i, line in lines
	regex.match(`\.createCipher\s*\(`, line)
	not contains(line, "createCipheriv")
	not contains(line, "//")
	finding := {
		"rule_id": metadata.id,
		"message": "crypto.createCipher() is deprecated and uses a static IV; replace with crypto.createCipheriv() and a random IV from crypto.randomBytes()",
		"artifact_uri": path,
		"severity": metadata.severity,
		"level": metadata.level,
		"start_line": i + 1,
		"snippet": line,
	}
}

findings contains finding if {
	some path in object.keys(input.file_contents)
	_is_js(path)
	not endswith(path, ".min.js")
	lines := split(input.file_contents[path], "\n")
	some i, line in lines
	regex.match(`\.createDecipher\s*\(`, line)
	not contains(line, "createDecipheriv")
	not contains(line, "//")
	finding := {
		"rule_id": metadata.id,
		"message": "crypto.createDecipher() is deprecated and uses a static IV; replace with crypto.createDecipheriv() and a random IV from crypto.randomBytes()",
		"artifact_uri": path,
		"severity": metadata.severity,
		"level": metadata.level,
		"start_line": i + 1,
		"snippet": line,
	}
}
