package vulnetix.rules.vnx_sec_177

import rego.v1
import data.vulnetix.lib.secrets

# GENERATED by internal/sast/secretsgen from catalog.json — do not edit by hand.

metadata := {
	"id": "VNX-SEC-177",
	"name": "DigitalOcean App Platform / function deploy URL (context)",
	"description": "A DigitalOcean deploy/trigger URL containing an embedded token under a DigitalOcean context was found. Such URLs can trigger deployments without further authentication.",
	"help_uri": "https://docs.cli.vulnetix.com/docs/sast-rules/secrets/cloud/#vnx-sec-177",
	"languages": [],
	"severity": "medium",
	"level": "warning",
	"kind": "secrets",
	"cwe": [798],
	"capec": ["CAPEC-191"],
	"attack_technique": ["T1552.001"],
	"cvssv4": "",
	"cwss": "CWSS:1.0/TI:M/AP:A/AL:M/IC:M/FC:M/RP:H/RL:H/AV:N/AS:L/IN:L/SC:N/CONF:N/T:A/P:M",
	"tags": ["secrets", "digitalocean", "cloud"],
}

_pattern := `(https://[a-z0-9.-]*\.ondigitalocean\.app/[A-Za-z0-9/_-]*\?[A-Za-z0-9=&_-]*token=[A-Za-z0-9_-]{16,})`
_keywords := ["ondigitalocean.app"]

findings contains finding if {
	some path in object.keys(input.file_contents)
	not secrets.skip_path(path)
	lines := split(input.file_contents[path], "\n")
	some i, line in lines
	secrets.has_keyword(line, _keywords)
	m := regex.find_all_string_submatch_n(_pattern, line, 1)
	count(m) > 0
	token := m[0][1]
	not secrets.is_example_token(token)
	finding := {
		"rule_id": metadata.id,
		"message": "DigitalOcean deploy/trigger URL with embedded token found; rotate the token in the DigitalOcean control panel",
		"artifact_uri": path,
		"severity": metadata.severity,
		"level": metadata.level,
		"start_line": i + 1,
		"snippet": secrets.redact(line),
	}
}
