package vulnetix.rules.vnx_sec_173

import rego.v1
import data.vulnetix.lib.secrets

# GENERATED by internal/sast/secretsgen from catalog.json — do not edit by hand.

metadata := {
	"id": "VNX-SEC-173",
	"name": "Akamai EdgeGrid access token (context)",
	"description": "An Akamai EdgeGrid access token (akab- prefix) under an Akamai context was found. It is part of the EdgeGrid credential set authorizing Akamai Open API calls.",
	"help_uri": "https://docs.cli.vulnetix.com/docs/sast-rules/secrets/cloud/#vnx-sec-173",
	"languages": [],
	"severity": "high",
	"level": "error",
	"kind": "secrets",
	"cwe": [798],
	"capec": ["CAPEC-191"],
	"attack_technique": ["T1552.001"],
	"cvssv4": "",
	"cwss": "CWSS:1.0/TI:H/AP:A/AL:M/IC:H/FC:H/RP:H/RL:H/AV:N/AS:L/IN:L/SC:N/CONF:N/T:A/P:M",
	"tags": ["secrets", "akamai", "cloud"],
}

_pattern := `(?i)(?:akamai|edgegrid)[a-z0-9_]*access[_-]?token\s*[:=]\s*['"]?(akab-[A-Za-z0-9]{16}-[A-Za-z0-9]{16})['"]?`
_keywords := ["akamai", "akab-"]

findings contains finding if {
	some path in object.keys(input.file_contents)
	not secrets.skip_path(path)
	lines := split(input.file_contents[path], "\n")
	some i, line in lines
	secrets.has_keyword(line, _keywords)
	m := regex.find_all_string_submatch_n(_pattern, line, 1)
	count(m) > 0
	token := m[0][1]
	not secrets.is_example_token(token)
	finding := {
		"rule_id": metadata.id,
		"message": "Akamai EdgeGrid access token found; invalidate the API client in Akamai Control Center and recreate credentials",
		"artifact_uri": path,
		"severity": metadata.severity,
		"level": metadata.level,
		"start_line": i + 1,
		"snippet": secrets.redact(line),
	}
}
