package vulnetix.rules.vnx_sec_572

import rego.v1
import data.vulnetix.lib.secrets

# GENERATED by internal/sast/secretsgen from catalog.json — do not edit by hand.

metadata := {
	"id": "VNX-SEC-572",
	"name": "Elastic Cloud API key (base64)",
	"description": "An Elasticsearch / Elastic Cloud API key encoded as base64 id:api_key and assigned to a context keyword was found. It authenticates to Elasticsearch with the key's role descriptors.",
	"help_uri": "https://docs.cli.vulnetix.com/docs/sast-rules/secrets/database/#vnx-sec-572",
	"languages": [],
	"severity": "high",
	"level": "error",
	"kind": "secrets",
	"cwe": [798],
	"capec": ["CAPEC-191"],
	"attack_technique": ["T1552.001"],
	"cvssv4": "",
	"cwss": "CWSS:1.0/TI:H/AP:A/AL:M/IC:H/FC:H/RP:H/RL:H/AV:N/AS:L/IN:L/SC:N/CONF:N/T:A/P:M",
	"tags": ["secrets", "elastic", "database"],
}

_pattern := `(?i)(?:elastic|elasticsearch|es)[a-z0-9_]*api[_-]?key\s*[:=]\s*['"]?([A-Za-z0-9+/]{40,}={0,2})['"]?`
_keywords := ["elastic", "apikey"]

findings contains finding if {
	some path in object.keys(input.file_contents)
	not secrets.skip_path(path)
	lines := split(input.file_contents[path], "\n")
	some i, line in lines
	secrets.has_keyword(line, _keywords)
	m := regex.find_all_string_submatch_n(_pattern, line, 1)
	count(m) > 0
	token := m[0][1]
	not secrets.is_example_token(token)
	secrets.high_entropy(token, 3.8)
	finding := {
		"rule_id": metadata.id,
		"message": "Elastic Cloud API key found; invalidate it via the Elasticsearch security API or Kibana and create a new key with least privilege",
		"artifact_uri": path,
		"severity": metadata.severity,
		"level": metadata.level,
		"start_line": i + 1,
		"snippet": secrets.redact(line),
	}
}
