package vulnetix.rules.vnx_sec_700

import rego.v1
import data.vulnetix.lib.secrets

# GENERATED by internal/sast/secretsgen from catalog.json — do not edit by hand.

metadata := {
	"id": "VNX-SEC-700",
	"name": "Ethereum keystore JSON (V3 wallet)",
	"description": "An Ethereum V3 keystore JSON (crypto + ciphertext + kdf fields) assigned to a keystore context was found. It is an encrypted wallet file; brute-forcing the password recovers the private key.",
	"help_uri": "https://docs.cli.vulnetix.com/docs/sast-rules/secrets/crypto-blockchain/#vnx-sec-700",
	"languages": [],
	"severity": "high",
	"level": "error",
	"kind": "secrets",
	"cwe": [798],
	"capec": ["CAPEC-191"],
	"attack_technique": ["T1552.001"],
	"cvssv4": "",
	"cwss": "CWSS:1.0/TI:H/AP:A/AL:M/IC:H/FC:H/RP:H/RL:H/AV:N/AS:L/IN:L/SC:N/CONF:N/T:A/P:M",
	"tags": ["secrets", "ethereum", "crypto-blockchain"],
}

_pattern := `(?i)("crypto"\s*:\s*\{[^}]*"ciphertext"\s*:\s*"[0-9a-f]{64,}")`
_keywords := ["ciphertext", "keystore", "kdf"]

findings contains finding if {
	some path in object.keys(input.file_contents)
	not secrets.skip_path(path)
	lines := split(input.file_contents[path], "\n")
	some i, line in lines
	secrets.has_keyword(line, _keywords)
	m := regex.find_all_string_submatch_n(_pattern, line, 1)
	count(m) > 0
	token := m[0][1]
	not secrets.is_example_token(token)
	finding := {
		"rule_id": metadata.id,
		"message": "Ethereum V3 keystore found; move funds to a new wallet and never commit keystore files",
		"artifact_uri": path,
		"severity": metadata.severity,
		"level": metadata.level,
		"start_line": i + 1,
		"snippet": secrets.redact(line),
	}
}
