package vulnetix.rules.vnx_sec_102

import rego.v1
import data.vulnetix.lib.secrets

# GENERATED by internal/sast/secretsgen from catalog.json — do not edit by hand.

metadata := {
	"id": "VNX-SEC-102",
	"name": "Oracle Cloud (OCI) auth token",
	"description": "An Oracle Cloud Infrastructure user auth token assigned to a context keyword was found. OCI auth tokens are used for Swift/object-storage and other token-based API authentication.",
	"help_uri": "https://docs.cli.vulnetix.com/docs/sast-rules/secrets/cloud/#vnx-sec-102",
	"languages": [],
	"severity": "high",
	"level": "error",
	"kind": "secrets",
	"cwe": [798],
	"capec": ["CAPEC-191"],
	"attack_technique": ["T1552.001"],
	"cvssv4": "",
	"cwss": "CWSS:1.0/TI:H/AP:A/AL:M/IC:H/FC:H/RP:H/RL:H/AV:N/AS:L/IN:L/SC:N/CONF:N/T:A/P:M",
	"tags": ["secrets", "oracle", "cloud"],
}

_pattern := `(?i)(?:oci|oracle)[a-z0-9_]*(?:auth[_-]?token|token)[a-z0-9_]*\s*[:=]\s*['"]?([A-Za-z0-9+/=._-]{32,})['"]?`
_keywords := ["oci", "oracle"]

findings contains finding if {
	some path in object.keys(input.file_contents)
	not secrets.skip_path(path)
	lines := split(input.file_contents[path], "\n")
	some i, line in lines
	secrets.has_keyword(line, _keywords)
	m := regex.find_all_string_submatch_n(_pattern, line, 1)
	count(m) > 0
	token := m[0][1]
	not secrets.is_example_token(token)
	secrets.high_entropy(token, 3.5)
	finding := {
		"rule_id": metadata.id,
		"message": "Oracle Cloud auth token found; delete it under the OCI user's Auth Tokens and generate a replacement",
		"artifact_uri": path,
		"severity": metadata.severity,
		"level": metadata.level,
		"start_line": i + 1,
		"snippet": secrets.redact(line),
	}
}
