package vulnetix.rules.vnx_sec_383

import rego.v1
import data.vulnetix.lib.secrets

# GENERATED by internal/sast/secretsgen from catalog.json — do not edit by hand.

metadata := {
	"id": "VNX-SEC-383",
	"name": "Klarna API username (PK)",
	"description": "A Klarna API username using the PK... merchant-id form was found near a klarna assignment. It is paired with an API password for HTTP Basic auth.",
	"help_uri": "https://docs.cli.vulnetix.com/docs/sast-rules/secrets/payment/#vnx-sec-383",
	"languages": [],
	"severity": "medium",
	"level": "warning",
	"kind": "secrets",
	"cwe": [798],
	"capec": ["CAPEC-191"],
	"attack_technique": ["T1552.001"],
	"cvssv4": "",
	"cwss": "CWSS:1.0/TI:M/AP:A/AL:M/IC:M/FC:M/RP:H/RL:H/AV:N/AS:L/IN:L/SC:N/CONF:N/T:A/P:M",
	"tags": ["secrets", "klarna", "payment"],
}

_pattern := `(?i)klarna[a-z0-9_]*(?:username|user|merchant)[a-z0-9_]*\s*[:=]\s*['"]?(PK[A-Za-z0-9]{10,40})['"]?`
_keywords := ["klarna", "pk"]

findings contains finding if {
	some path in object.keys(input.file_contents)
	not secrets.skip_path(path)
	lines := split(input.file_contents[path], "\n")
	some i, line in lines
	secrets.has_keyword(line, _keywords)
	m := regex.find_all_string_submatch_n(_pattern, line, 1)
	count(m) > 0
	token := m[0][1]
	not secrets.is_example_token(token)
	secrets.high_entropy(token, 3.4)
	finding := {
		"rule_id": metadata.id,
		"message": "Klarna API username found; confirm the paired API password was not committed and rotate in the Klarna Merchant Portal if so",
		"artifact_uri": path,
		"severity": metadata.severity,
		"level": metadata.level,
		"start_line": i + 1,
		"snippet": secrets.redact(line),
	}
}
