package vulnetix.rules.vnx_sec_1031

import rego.v1
import data.vulnetix.lib.secrets

# GENERATED by internal/sast/secretsgen from catalog.json — do not edit by hand.

metadata := {
	"id": "VNX-SEC-1031",
	"name": "HCP Vault Secrets / HCP API client secret (assignment)",
	"description": "A HashiCorp Cloud Platform client secret assigned to an hcp secret field was found. With the client ID it obtains an HCP access token granting access to HCP Vault Secrets and other HCP services.",
	"help_uri": "https://docs.cli.vulnetix.com/docs/sast-rules/secrets/saas/#vnx-sec-1031",
	"languages": [],
	"severity": "critical",
	"level": "error",
	"kind": "secrets",
	"cwe": [798],
	"capec": ["CAPEC-191"],
	"attack_technique": ["T1552.001"],
	"cvssv4": "",
	"cwss": "CWSS:1.0/TI:H/AP:A/AL:H/IC:H/FC:H/RP:H/RL:H/AV:N/AS:L/IN:L/SC:N/CONF:N/T:A/P:H",
	"tags": ["secrets", "hcp", "saas"],
}

_pattern := `(?i)hcp[a-z0-9_]*(?:client[_-]?secret|secret)\s*[:=]\s*['"]?([A-Za-z0-9_-]{40,80})['"]?`
_keywords := ["hcp", "secret"]

findings contains finding if {
	some path in object.keys(input.file_contents)
	not secrets.skip_path(path)
	lines := split(input.file_contents[path], "\n")
	some i, line in lines
	secrets.has_keyword(line, _keywords)
	m := regex.find_all_string_submatch_n(_pattern, line, 1)
	count(m) > 0
	token := m[0][1]
	not secrets.is_example_token(token)
	secrets.high_entropy(token, 4)
	finding := {
		"rule_id": metadata.id,
		"message": "HCP client secret found; rotate the service principal in the HCP portal under Access control",
		"artifact_uri": path,
		"severity": metadata.severity,
		"level": metadata.level,
		"start_line": i + 1,
		"snippet": secrets.redact(line),
	}
}
