package vulnetix.rules.vnx_sec_732

import rego.v1
import data.vulnetix.lib.secrets

# GENERATED by internal/sast/secretsgen from catalog.json — do not edit by hand.

metadata := {
	"id": "VNX-SEC-732",
	"name": "Hardcoded encryption key (AES/Fernet context)",
	"description": "A hardcoded symmetric encryption key assigned to an encryption-key/aes/fernet variable was found. Exposure of the key allows decryption of all data it protects.",
	"help_uri": "https://docs.cli.vulnetix.com/docs/sast-rules/secrets/private-keys/#vnx-sec-732",
	"languages": [],
	"severity": "high",
	"level": "error",
	"kind": "secrets",
	"cwe": [798],
	"capec": ["CAPEC-191"],
	"attack_technique": ["T1552.001"],
	"cvssv4": "",
	"cwss": "CWSS:1.0/TI:H/AP:A/AL:M/IC:H/FC:H/RP:H/RL:H/AV:N/AS:L/IN:L/SC:N/CONF:N/T:A/P:M",
	"tags": ["secrets", "encryption-key", "private-keys"],
}

_pattern := `(?i)(?:encryption[_-]?key|aes[_-]?key|fernet[_-]?key|secret[_-]?box[_-]?key)\s*[:=]\s*["']([A-Za-z0-9+/=_-]{16,})["']`
_keywords := ["encryption_key", "aes key", "fernet", "secret box"]

findings contains finding if {
	some path in object.keys(input.file_contents)
	not secrets.skip_path(path)
	lines := split(input.file_contents[path], "\n")
	some i, line in lines
	secrets.has_keyword(line, _keywords)
	m := regex.find_all_string_submatch_n(_pattern, line, 1)
	count(m) > 0
	token := m[0][1]
	not secrets.is_example_token(token)
	secrets.high_entropy(token, 3.5)
	finding := {
		"rule_id": metadata.id,
		"message": "Hardcoded encryption key found; rotate the key and re-encrypt any data protected by it",
		"artifact_uri": path,
		"severity": metadata.severity,
		"level": metadata.level,
		"start_line": i + 1,
		"snippet": secrets.redact(line),
	}
}
