package vulnetix.rules.vnx_sec_152

import rego.v1
import data.vulnetix.lib.secrets

# GENERATED by internal/sast/secretsgen from catalog.json — do not edit by hand.

metadata := {
	"id": "VNX-SEC-152",
	"name": "Cloudflare Global API key (legacy 37-hex)",
	"description": "A Cloudflare legacy Global API Key appearing alongside a Cloudflare email/key context was found. The Global API Key grants full account-wide access and cannot be scoped.",
	"help_uri": "https://docs.cli.vulnetix.com/docs/sast-rules/secrets/cloud/#vnx-sec-152",
	"languages": [],
	"severity": "critical",
	"level": "error",
	"kind": "secrets",
	"cwe": [798],
	"capec": ["CAPEC-191"],
	"attack_technique": ["T1552.001"],
	"cvssv4": "",
	"cwss": "CWSS:1.0/TI:H/AP:A/AL:H/IC:H/FC:H/RP:H/RL:H/AV:N/AS:L/IN:L/SC:N/CONF:N/T:A/P:H",
	"tags": ["secrets", "cloudflare", "cloud"],
}

_pattern := `(?i)(?:cloudflare|cf)[a-z0-9_]*(?:api[_-]?key|global[_-]?key|key)\s*[:=]\s*['"]?([0-9a-f]{37})['"]?`
_keywords := ["cloudflare", "cf"]

findings contains finding if {
	some path in object.keys(input.file_contents)
	not secrets.skip_path(path)
	lines := split(input.file_contents[path], "\n")
	some i, line in lines
	secrets.has_keyword(line, _keywords)
	m := regex.find_all_string_submatch_n(_pattern, line, 1)
	count(m) > 0
	token := m[0][1]
	not secrets.is_example_token(token)
	secrets.high_entropy(token, 3)
	finding := {
		"rule_id": metadata.id,
		"message": "Cloudflare Global API Key found; roll it in the Cloudflare dashboard under My Profile \u003e API Tokens \u003e Global API Key and migrate to scoped tokens",
		"artifact_uri": path,
		"severity": metadata.severity,
		"level": metadata.level,
		"start_line": i + 1,
		"snippet": secrets.redact(line),
	}
}
