package vulnetix.rules.vnx_sec_909

import rego.v1
import data.vulnetix.lib.secrets

# GENERATED by internal/sast/secretsgen from catalog.json — do not edit by hand.

metadata := {
	"id": "VNX-SEC-909",
	"name": "Visual Crossing weather API key",
	"description": "A Visual Crossing Weather API key was found near a visualcrossing assignment. It is a 25-character uppercase-alphanumeric string authorizing timeline weather queries.",
	"help_uri": "https://docs.cli.vulnetix.com/docs/sast-rules/secrets/saas/#vnx-sec-909",
	"languages": [],
	"severity": "medium",
	"level": "warning",
	"kind": "secrets",
	"cwe": [798],
	"capec": ["CAPEC-191"],
	"attack_technique": ["T1552.001"],
	"cvssv4": "",
	"cwss": "CWSS:1.0/TI:M/AP:A/AL:M/IC:M/FC:M/RP:H/RL:H/AV:N/AS:L/IN:L/SC:N/CONF:N/T:A/P:M",
	"tags": ["secrets", "visualcrossing", "saas"],
}

_pattern := `(?i)(?:visualcrossing|visual[_-]?crossing)[a-z0-9_]*(?:api[_-]?key|apikey|key)[a-z0-9_]*\s*[:=]\s*['"]?([A-Z0-9]{25})['"]?`
_keywords := ["visualcrossing", "visual crossing"]

findings contains finding if {
	some path in object.keys(input.file_contents)
	not secrets.skip_path(path)
	lines := split(input.file_contents[path], "\n")
	some i, line in lines
	secrets.has_keyword(line, _keywords)
	m := regex.find_all_string_submatch_n(_pattern, line, 1)
	count(m) > 0
	token := m[0][1]
	not secrets.is_example_token(token)
	secrets.high_entropy(token, 3.5)
	finding := {
		"rule_id": metadata.id,
		"message": "Visual Crossing weather API key found; rotate it in the Visual Crossing account under Account \u003e Key",
		"artifact_uri": path,
		"severity": metadata.severity,
		"level": metadata.level,
		"start_line": i + 1,
		"snippet": secrets.redact(line),
	}
}
