package vulnetix.rules.vnx_sec_128

import rego.v1
import data.vulnetix.lib.secrets

# GENERATED by internal/sast/secretsgen from catalog.json — do not edit by hand.

metadata := {
	"id": "VNX-SEC-128",
	"name": "Azure Container Registry password",
	"description": "An Azure Container Registry (ACR) admin password assigned to a context keyword was found. ACR admin credentials grant push/pull access to all repositories in the registry.",
	"help_uri": "https://docs.cli.vulnetix.com/docs/sast-rules/secrets/cloud/#vnx-sec-128",
	"languages": [],
	"severity": "high",
	"level": "error",
	"kind": "secrets",
	"cwe": [798],
	"capec": ["CAPEC-191"],
	"attack_technique": ["T1552.001"],
	"cvssv4": "",
	"cwss": "CWSS:1.0/TI:H/AP:A/AL:M/IC:H/FC:H/RP:H/RL:H/AV:N/AS:L/IN:L/SC:N/CONF:N/T:A/P:M",
	"tags": ["secrets", "azure", "cloud"],
}

_pattern := `(?i)(?:acr|azurecr)[a-z0-9_]*(?:password|passwd|token)\s*[:=]\s*['"]?([A-Za-z0-9+/=]{30,})['"]?`
_keywords := ["acr", "azurecr"]

findings contains finding if {
	some path in object.keys(input.file_contents)
	not secrets.skip_path(path)
	lines := split(input.file_contents[path], "\n")
	some i, line in lines
	secrets.has_keyword(line, _keywords)
	m := regex.find_all_string_submatch_n(_pattern, line, 1)
	count(m) > 0
	token := m[0][1]
	not secrets.is_example_token(token)
	secrets.high_entropy(token, 3.8)
	finding := {
		"rule_id": metadata.id,
		"message": "Azure Container Registry password found; regenerate the admin password in the ACR access keys, or disable admin user and use tokens",
		"artifact_uri": path,
		"severity": metadata.severity,
		"level": metadata.level,
		"start_line": i + 1,
		"snippet": secrets.redact(line),
	}
}
