package vulnetix.rules.vnx_sec_1114

import rego.v1
import data.vulnetix.lib.secrets

# GENERATED by internal/sast/secretsgen from catalog.json — do not edit by hand.

metadata := {
	"id": "VNX-SEC-1114",
	"name": "SoundCloud OAuth access token",
	"description": "A SoundCloud OAuth access token (oauth-prefixed numeric/hex) was found. It authorizes SoundCloud API actions on behalf of the authorized user.",
	"help_uri": "https://docs.cli.vulnetix.com/docs/sast-rules/secrets/saas/#vnx-sec-1114",
	"languages": [],
	"severity": "high",
	"level": "error",
	"kind": "secrets",
	"cwe": [798],
	"capec": ["CAPEC-191"],
	"attack_technique": ["T1552.001"],
	"cvssv4": "",
	"cwss": "CWSS:1.0/TI:H/AP:A/AL:M/IC:H/FC:H/RP:H/RL:H/AV:N/AS:L/IN:L/SC:N/CONF:N/T:A/P:M",
	"tags": ["secrets", "soundcloud", "saas"],
}

_pattern := `(?i)soundcloud[a-z0-9_]*(?:access[_-]?token|oauth[_-]?token)\s*[:=]\s*['"]?([0-9]{1,12}-[0-9]{1,12}-[0-9]{1,12}-[0-9a-f]{20,40})['"]?`
_keywords := ["soundcloud", "accesstoken"]

findings contains finding if {
	some path in object.keys(input.file_contents)
	not secrets.skip_path(path)
	lines := split(input.file_contents[path], "\n")
	some i, line in lines
	secrets.has_keyword(line, _keywords)
	m := regex.find_all_string_submatch_n(_pattern, line, 1)
	count(m) > 0
	token := m[0][1]
	not secrets.is_example_token(token)
	secrets.high_entropy(token, 3)
	finding := {
		"rule_id": metadata.id,
		"message": "SoundCloud OAuth access token found; revoke the app authorization and rotate the client secret",
		"artifact_uri": path,
		"severity": metadata.severity,
		"level": metadata.level,
		"start_line": i + 1,
		"snippet": secrets.redact(line),
	}
}
