package vulnetix.rules.vnx_sec_099

import rego.v1
import data.vulnetix.lib.secrets

# GENERATED by internal/sast/secretsgen from catalog.json — do not edit by hand.

metadata := {
	"id": "VNX-SEC-099",
	"name": "Zapier webhook URL",
	"description": "A Zapier catch-hook webhook URL was found, allowing arbitrary data to be injected into the user's Zaps.",
	"help_uri": "https://docs.cli.vulnetix.com/docs/sast-rules/secrets/webhooks/#vnx-sec-099",
	"languages": [],
	"severity": "high",
	"level": "error",
	"kind": "secrets",
	"cwe": [798],
	"capec": ["CAPEC-191"],
	"attack_technique": ["T1552.001"],
	"cvssv4": "",
	"cwss": "CWSS:1.0/TI:H/AP:A/AL:M/IC:H/FC:H/RP:H/RL:H/AV:N/AS:L/IN:L/SC:N/CONF:N/T:A/P:M",
	"tags": ["secrets", "zapier", "webhook"],
}

_pattern := `(https://hooks\.zapier\.com/hooks/catch/[0-9]+/[A-Za-z0-9]+)`
_keywords := ["hooks.zapier.com"]

findings contains finding if {
	some path in object.keys(input.file_contents)
	not secrets.skip_path(path)
	lines := split(input.file_contents[path], "\n")
	some i, line in lines
	secrets.has_keyword(line, _keywords)
	m := regex.find_all_string_submatch_n(_pattern, line, 1)
	count(m) > 0
	token := m[0][1]
	not secrets.is_example_token(token)
	finding := {
		"rule_id": metadata.id,
		"message": "Zapier webhook URL found; regenerate the trigger in Zapier to invalidate it",
		"artifact_uri": path,
		"severity": metadata.severity,
		"level": metadata.level,
		"start_line": i + 1,
		"snippet": secrets.redact(line),
	}
}
