package vulnetix.rules.vnx_sec_698

import rego.v1
import data.vulnetix.lib.secrets

# GENERATED by internal/sast/secretsgen from catalog.json — do not edit by hand.

metadata := {
	"id": "VNX-SEC-698",
	"name": "BscScan/Etherscan-family multichain key (V2)",
	"description": "An Etherscan V2 multichain API key assigned to a scanner context was found. A single V2 key authorises access across Etherscan-family explorers (ETH, BSC, Polygon, etc).",
	"help_uri": "https://docs.cli.vulnetix.com/docs/sast-rules/secrets/crypto-blockchain/#vnx-sec-698",
	"languages": [],
	"severity": "medium",
	"level": "warning",
	"kind": "secrets",
	"cwe": [798],
	"capec": ["CAPEC-191"],
	"attack_technique": ["T1552.001"],
	"cvssv4": "",
	"cwss": "CWSS:1.0/TI:M/AP:A/AL:M/IC:M/FC:M/RP:H/RL:H/AV:N/AS:L/IN:L/SC:N/CONF:N/T:A/P:M",
	"tags": ["secrets", "etherscan", "crypto-blockchain"],
}

_pattern := `(?i)(?:etherscan|explorer)[_-]?(?:v2[_-]?)?api[_-]?key\s*[:=]\s*["']?([A-Z0-9]{30,40})["']?`
_keywords := ["etherscan", "explorer", "api key"]

findings contains finding if {
	some path in object.keys(input.file_contents)
	not secrets.skip_path(path)
	lines := split(input.file_contents[path], "\n")
	some i, line in lines
	secrets.has_keyword(line, _keywords)
	m := regex.find_all_string_submatch_n(_pattern, line, 1)
	count(m) > 0
	token := m[0][1]
	not secrets.is_example_token(token)
	secrets.high_entropy(token, 3.5)
	finding := {
		"rule_id": metadata.id,
		"message": "Etherscan V2 multichain API key found; revoke it in the Etherscan account and rotate",
		"artifact_uri": path,
		"severity": metadata.severity,
		"level": metadata.level,
		"start_line": i + 1,
		"snippet": secrets.redact(line),
	}
}
