package vulnetix.rules.vnx_sec_640

import rego.v1
import data.vulnetix.lib.secrets

# GENERATED by internal/sast/secretsgen from catalog.json — do not edit by hand.

metadata := {
	"id": "VNX-SEC-640",
	"name": "Sumo Logic HTTP source collector URL",
	"description": "A Sumo Logic HTTP source collector endpoint URL embedding the per-source upload secret path was found. Anyone with the URL can push arbitrary log/metric data to the Sumo Logic source.",
	"help_uri": "https://docs.cli.vulnetix.com/docs/sast-rules/secrets/monitoring/#vnx-sec-640",
	"languages": [],
	"severity": "high",
	"level": "error",
	"kind": "secrets",
	"cwe": [798],
	"capec": ["CAPEC-191"],
	"attack_technique": ["T1552.001"],
	"cvssv4": "",
	"cwss": "CWSS:1.0/TI:H/AP:A/AL:M/IC:H/FC:H/RP:H/RL:H/AV:N/AS:L/IN:L/SC:N/CONF:N/T:A/P:M",
	"tags": ["secrets", "sumologic", "monitoring"],
}

_pattern := `(?i)https:\/\/(?:endpoint[0-9]*\.)?collection\.[a-z0-9.-]*sumologic\.com\/receiver\/v1\/http\/([A-Za-z0-9_=-]{40,})`
_keywords := ["sumologic.com/receiver"]

findings contains finding if {
	some path in object.keys(input.file_contents)
	not secrets.skip_path(path)
	lines := split(input.file_contents[path], "\n")
	some i, line in lines
	secrets.has_keyword(line, _keywords)
	m := regex.find_all_string_submatch_n(_pattern, line, 1)
	count(m) > 0
	token := m[0][1]
	not secrets.is_example_token(token)
	finding := {
		"rule_id": metadata.id,
		"message": "Sumo Logic HTTP source URL found; rotate the HTTP source in Sumo Logic (delete and recreate the source) to invalidate the leaked endpoint",
		"artifact_uri": path,
		"severity": metadata.severity,
		"level": metadata.level,
		"start_line": i + 1,
		"snippet": secrets.redact(line),
	}
}
