package vulnetix.rules.vnx_sec_408

import rego.v1
import data.vulnetix.lib.secrets

# GENERATED by internal/sast/secretsgen from catalog.json — do not edit by hand.

metadata := {
	"id": "VNX-SEC-408",
	"name": "MessageBird/Bird access key",
	"description": "A MessageBird (Bird) API access key was found near a messagebird assignment. It is a 25-character alphanumeric key that authorizes SMS and messaging operations.",
	"help_uri": "https://docs.cli.vulnetix.com/docs/sast-rules/secrets/communication/#vnx-sec-408",
	"languages": [],
	"severity": "high",
	"level": "error",
	"kind": "secrets",
	"cwe": [798],
	"capec": ["CAPEC-191"],
	"attack_technique": ["T1552.001"],
	"cvssv4": "",
	"cwss": "CWSS:1.0/TI:H/AP:A/AL:M/IC:H/FC:H/RP:H/RL:H/AV:N/AS:L/IN:L/SC:N/CONF:N/T:A/P:M",
	"tags": ["secrets", "messagebird", "communication"],
}

_pattern := `(?i)(?:messagebird|message_bird|\bbird)[a-z0-9_]*(?:access[_-]?key|api[_-]?key|apikey|key|token)[a-z0-9_]*\s*[:=]\s*['"]?([A-Za-z0-9]{25})['"]?`
_keywords := ["messagebird", "bird"]

findings contains finding if {
	some path in object.keys(input.file_contents)
	not secrets.skip_path(path)
	lines := split(input.file_contents[path], "\n")
	some i, line in lines
	secrets.has_keyword(line, _keywords)
	m := regex.find_all_string_submatch_n(_pattern, line, 1)
	count(m) > 0
	token := m[0][1]
	not secrets.is_example_token(token)
	secrets.high_entropy(token, 3.5)
	finding := {
		"rule_id": metadata.id,
		"message": "MessageBird/Bird access key found; revoke it in the Bird dashboard under Developers \u003e API access",
		"artifact_uri": path,
		"severity": metadata.severity,
		"level": metadata.level,
		"start_line": i + 1,
		"snippet": secrets.redact(line),
	}
}
