package vulnetix.rules.vnx_sec_430

import rego.v1
import data.vulnetix.lib.secrets

# GENERATED by internal/sast/secretsgen from catalog.json — do not edit by hand.

metadata := {
	"id": "VNX-SEC-430",
	"name": "Customer.io tracking/app API key",
	"description": "A Customer.io API key (site key, track key, or App API bearer) was found near a customerio assignment. These authorize event tracking and transactional messaging.",
	"help_uri": "https://docs.cli.vulnetix.com/docs/sast-rules/secrets/communication/#vnx-sec-430",
	"languages": [],
	"severity": "high",
	"level": "error",
	"kind": "secrets",
	"cwe": [798],
	"capec": ["CAPEC-191"],
	"attack_technique": ["T1552.001"],
	"cvssv4": "",
	"cwss": "CWSS:1.0/TI:H/AP:A/AL:M/IC:H/FC:H/RP:H/RL:H/AV:N/AS:L/IN:L/SC:N/CONF:N/T:A/P:M",
	"tags": ["secrets", "customerio", "communication"],
}

_pattern := `(?i)customer[._]?io[a-z0-9_]*(?:site[_-]?id|track[_-]?key|app[_-]?api[_-]?key|api[_-]?key|apikey|key|token)[a-z0-9_]*\s*[:=]\s*['"]?([A-Za-z0-9]{20,64})['"]?`
_keywords := ["customer.io", "customerio", "customer_io"]

findings contains finding if {
	some path in object.keys(input.file_contents)
	not secrets.skip_path(path)
	lines := split(input.file_contents[path], "\n")
	some i, line in lines
	secrets.has_keyword(line, _keywords)
	m := regex.find_all_string_submatch_n(_pattern, line, 1)
	count(m) > 0
	token := m[0][1]
	not secrets.is_example_token(token)
	secrets.high_entropy(token, 3.8)
	finding := {
		"rule_id": metadata.id,
		"message": "Customer.io API key found; rotate it in the Customer.io workspace settings under API Credentials",
		"artifact_uri": path,
		"severity": metadata.severity,
		"level": metadata.level,
		"start_line": i + 1,
		"snippet": secrets.redact(line),
	}
}
