package vulnetix.rules.vnx_sec_458

import rego.v1
import data.vulnetix.lib.secrets

# GENERATED by internal/sast/secretsgen from catalog.json — do not edit by hand.

metadata := {
	"id": "VNX-SEC-458",
	"name": "Twilio SendGrid subuser SMTP password",
	"description": "A SendGrid SMTP credential (SG. API key used as the SMTP password for a subuser) was found near an smtp assignment. It allows relaying mail through SendGrid.",
	"help_uri": "https://docs.cli.vulnetix.com/docs/sast-rules/secrets/communication/#vnx-sec-458",
	"languages": [],
	"severity": "high",
	"level": "error",
	"kind": "secrets",
	"cwe": [798],
	"capec": ["CAPEC-191"],
	"attack_technique": ["T1552.001"],
	"cvssv4": "",
	"cwss": "CWSS:1.0/TI:H/AP:A/AL:M/IC:H/FC:H/RP:H/RL:H/AV:N/AS:L/IN:L/SC:N/CONF:N/T:A/P:M",
	"tags": ["secrets", "sendgrid", "communication"],
}

_pattern := `(?i)(?:smtp[_-]?pass|smtp[_-]?password|sendgrid)[a-z0-9_]*\s*[:=]\s*['"]?(SG\.[A-Za-z0-9_-]{20,30}\.[A-Za-z0-9_-]{40,50})['"]?`
_keywords := ["smtp", "sg."]

findings contains finding if {
	some path in object.keys(input.file_contents)
	not secrets.skip_path(path)
	lines := split(input.file_contents[path], "\n")
	some i, line in lines
	secrets.has_keyword(line, _keywords)
	m := regex.find_all_string_submatch_n(_pattern, line, 1)
	count(m) > 0
	token := m[0][1]
	not secrets.is_example_token(token)
	secrets.high_entropy(token, 3.8)
	finding := {
		"rule_id": metadata.id,
		"message": "SendGrid SMTP credential found; revoke the underlying API key in the SendGrid dashboard under Settings \u003e API Keys",
		"artifact_uri": path,
		"severity": metadata.severity,
		"level": metadata.level,
		"start_line": i + 1,
		"snippet": secrets.redact(line),
	}
}
