package vulnetix.rules.vnx_sec_944

import rego.v1
import data.vulnetix.lib.secrets

# GENERATED by internal/sast/secretsgen from catalog.json — do not edit by hand.

metadata := {
	"id": "VNX-SEC-944",
	"name": "LiveKit API secret",
	"description": "A LiveKit API secret was found near a livekit assignment. The secret pairs with the API key (prefix APIxxxx) to sign access tokens; a leaked secret lets an attacker mint valid room tokens.",
	"help_uri": "https://docs.cli.vulnetix.com/docs/sast-rules/secrets/saas/#vnx-sec-944",
	"languages": [],
	"severity": "critical",
	"level": "error",
	"kind": "secrets",
	"cwe": [798],
	"capec": ["CAPEC-191"],
	"attack_technique": ["T1552.001"],
	"cvssv4": "",
	"cwss": "CWSS:1.0/TI:H/AP:A/AL:H/IC:H/FC:H/RP:H/RL:H/AV:N/AS:L/IN:L/SC:N/CONF:N/T:A/P:H",
	"tags": ["secrets", "livekit", "saas"],
}

_pattern := `(?i)livekit[a-z0-9_]*(?:api[_-]?secret|secret|api[_-]?key|key)[a-z0-9_]*\s*[:=]\s*['"]?([A-Za-z0-9]{32,})['"]?`
_keywords := ["livekit"]

findings contains finding if {
	some path in object.keys(input.file_contents)
	not secrets.skip_path(path)
	lines := split(input.file_contents[path], "\n")
	some i, line in lines
	secrets.has_keyword(line, _keywords)
	m := regex.find_all_string_submatch_n(_pattern, line, 1)
	count(m) > 0
	token := m[0][1]
	not secrets.is_example_token(token)
	secrets.high_entropy(token, 3.7)
	finding := {
		"rule_id": metadata.id,
		"message": "LiveKit API secret found; rotate the key/secret pair in the LiveKit Cloud dashboard under Settings \u003e Keys",
		"artifact_uri": path,
		"severity": metadata.severity,
		"level": metadata.level,
		"start_line": i + 1,
		"snippet": secrets.redact(line),
	}
}
