package vulnetix.rules.vnx_sec_457

import rego.v1
import data.vulnetix.lib.secrets

# GENERATED by internal/sast/secretsgen from catalog.json — do not edit by hand.

metadata := {
	"id": "VNX-SEC-457",
	"name": "Microsoft Teams incoming webhook URL (Power Automate)",
	"description": "A Microsoft Teams / Power Automate workflow webhook URL was found. Anyone with the URL can post messages into the target Teams channel.",
	"help_uri": "https://docs.cli.vulnetix.com/docs/sast-rules/secrets/webhooks/#vnx-sec-457",
	"languages": [],
	"severity": "high",
	"level": "error",
	"kind": "secrets",
	"cwe": [798],
	"capec": ["CAPEC-191"],
	"attack_technique": ["T1552.001"],
	"cvssv4": "",
	"cwss": "CWSS:1.0/TI:H/AP:A/AL:M/IC:H/FC:H/RP:H/RL:H/AV:N/AS:L/IN:L/SC:N/CONF:N/T:A/P:M",
	"tags": ["secrets", "microsoft-teams", "webhooks"],
}

_pattern := `(https?://[a-z0-9.-]+\.logic\.azure\.com:443/workflows/[a-f0-9]{32}/triggers/[A-Za-z0-9_]+/paths/invoke[^\s'"]*sig=[A-Za-z0-9%_-]{20,})`
_keywords := ["logic.azure.com", "workflows", "triggers/manual"]

findings contains finding if {
	some path in object.keys(input.file_contents)
	not secrets.skip_path(path)
	lines := split(input.file_contents[path], "\n")
	some i, line in lines
	secrets.has_keyword(line, _keywords)
	m := regex.find_all_string_submatch_n(_pattern, line, 1)
	count(m) > 0
	token := m[0][1]
	not secrets.is_example_token(token)
	finding := {
		"rule_id": metadata.id,
		"message": "Microsoft Teams workflow webhook URL found; delete the Power Automate flow / webhook connector to invalidate the signed URL",
		"artifact_uri": path,
		"severity": metadata.severity,
		"level": metadata.level,
		"start_line": i + 1,
		"snippet": secrets.redact(line),
	}
}
