package vulnetix.rules.vnx_sec_404

import rego.v1
import data.vulnetix.lib.secrets

# GENERATED by internal/sast/secretsgen from catalog.json — do not edit by hand.

metadata := {
	"id": "VNX-SEC-404",
	"name": "Mailjet API key (public)",
	"description": "A Mailjet API key (the public half of the Basic Auth pair) was found near a mailjet assignment. It is a 32-character hex string used as the username for the Mailjet API.",
	"help_uri": "https://docs.cli.vulnetix.com/docs/sast-rules/secrets/communication/#vnx-sec-404",
	"languages": [],
	"severity": "medium",
	"level": "warning",
	"kind": "secrets",
	"cwe": [798],
	"capec": ["CAPEC-191"],
	"attack_technique": ["T1552.001"],
	"cvssv4": "",
	"cwss": "CWSS:1.0/TI:M/AP:A/AL:M/IC:M/FC:M/RP:H/RL:H/AV:N/AS:L/IN:L/SC:N/CONF:N/T:A/P:M",
	"tags": ["secrets", "mailjet", "communication"],
}

_pattern := `(?i)mailjet[a-z0-9_]*(?:api[_-]?key|apikey|public|key)[a-z0-9_]*\s*[:=]\s*['"]?([a-f0-9]{32})['"]?`
_keywords := ["mailjet"]

findings contains finding if {
	some path in object.keys(input.file_contents)
	not secrets.skip_path(path)
	lines := split(input.file_contents[path], "\n")
	some i, line in lines
	secrets.has_keyword(line, _keywords)
	m := regex.find_all_string_submatch_n(_pattern, line, 1)
	count(m) > 0
	token := m[0][1]
	not secrets.is_example_token(token)
	secrets.high_entropy(token, 3.5)
	finding := {
		"rule_id": metadata.id,
		"message": "Mailjet API key found; verify the paired secret key was not committed and rotate both under Account Settings \u003e REST API \u003e API Key Management",
		"artifact_uri": path,
		"severity": metadata.severity,
		"level": metadata.level,
		"start_line": i + 1,
		"snippet": secrets.redact(line),
	}
}
