package vulnetix.rules.vnx_sec_191

import rego.v1
import data.vulnetix.lib.secrets

# GENERATED by internal/sast/secretsgen from catalog.json — do not edit by hand.

metadata := {
	"id": "VNX-SEC-191",
	"name": "Jenkins crumb (CSRF token)",
	"description": "A Jenkins CSRF crumb value was found embedded in source. While short-lived, leaked crumbs combined with a session can enable CSRF-protected API calls.",
	"help_uri": "https://docs.cli.vulnetix.com/docs/sast-rules/secrets/source-control/#vnx-sec-191",
	"languages": [],
	"severity": "medium",
	"level": "warning",
	"kind": "secrets",
	"cwe": [798],
	"capec": ["CAPEC-191"],
	"attack_technique": ["T1552.001"],
	"cvssv4": "",
	"cwss": "CWSS:1.0/TI:M/AP:A/AL:M/IC:M/FC:M/RP:H/RL:H/AV:N/AS:L/IN:L/SC:N/CONF:N/T:A/P:M",
	"tags": ["secrets", "jenkins", "source-control"],
}

_pattern := `(?i)(?:jenkins[_-]?crumb|crumb)[a-z0-9_.]*\s*[:=]\s*['"]?([a-f0-9]{32,64})['"]?`
_keywords := ["crumb"]

findings contains finding if {
	some path in object.keys(input.file_contents)
	not secrets.skip_path(path)
	lines := split(input.file_contents[path], "\n")
	some i, line in lines
	secrets.has_keyword(line, _keywords)
	m := regex.find_all_string_submatch_n(_pattern, line, 1)
	count(m) > 0
	token := m[0][1]
	not secrets.is_example_token(token)
	secrets.high_entropy(token, 3.4)
	finding := {
		"rule_id": metadata.id,
		"message": "Jenkins crumb found in source; do not hardcode CSRF crumbs, fetch them at runtime from /crumbIssuer",
		"artifact_uri": path,
		"severity": metadata.severity,
		"level": metadata.level,
		"start_line": i + 1,
		"snippet": secrets.redact(line),
	}
}
