package vulnetix.rules.vnx_sec_162

import rego.v1
import data.vulnetix.lib.secrets

# GENERATED by internal/sast/secretsgen from catalog.json — do not edit by hand.

metadata := {
	"id": "VNX-SEC-162",
	"name": "OVH application key (context)",
	"description": "An OVH API application key under an OVH context keyword was found. The application key identifies the API application and pairs with the application secret and consumer key.",
	"help_uri": "https://docs.cli.vulnetix.com/docs/sast-rules/secrets/cloud/#vnx-sec-162",
	"languages": [],
	"severity": "medium",
	"level": "warning",
	"kind": "secrets",
	"cwe": [798],
	"capec": ["CAPEC-191"],
	"attack_technique": ["T1552.001"],
	"cvssv4": "",
	"cwss": "CWSS:1.0/TI:M/AP:A/AL:M/IC:M/FC:M/RP:H/RL:H/AV:N/AS:L/IN:L/SC:N/CONF:N/T:A/P:M",
	"tags": ["secrets", "ovh", "cloud"],
}

_pattern := `(?i)(?:ovh)[a-z0-9_]*application[_-]?key\s*[:=]\s*['"]?([0-9a-zA-Z]{16})['"]?`
_keywords := ["ovh", "application"]

findings contains finding if {
	some path in object.keys(input.file_contents)
	not secrets.skip_path(path)
	lines := split(input.file_contents[path], "\n")
	some i, line in lines
	secrets.has_keyword(line, _keywords)
	m := regex.find_all_string_submatch_n(_pattern, line, 1)
	count(m) > 0
	token := m[0][1]
	not secrets.is_example_token(token)
	secrets.high_entropy(token, 3)
	finding := {
		"rule_id": metadata.id,
		"message": "OVH application key found; revoke the application credentials in the OVH API management console and recreate",
		"artifact_uri": path,
		"severity": metadata.severity,
		"level": metadata.level,
		"start_line": i + 1,
		"snippet": secrets.redact(line),
	}
}
