package vulnetix.rules.vnx_sec_749

import rego.v1
import data.vulnetix.lib.secrets

# GENERATED by internal/sast/secretsgen from catalog.json — do not edit by hand.

metadata := {
	"id": "VNX-SEC-749",
	"name": "ADP OAuth client secret",
	"description": "An ADP Workforce Now OAuth client secret was found. Combined with the client ID and SSL certificate it grants API access to ADP payroll and HR data.",
	"help_uri": "https://docs.cli.vulnetix.com/docs/sast-rules/secrets/saas/#vnx-sec-749",
	"languages": [],
	"severity": "high",
	"level": "error",
	"kind": "secrets",
	"cwe": [798],
	"capec": ["CAPEC-191"],
	"attack_technique": ["T1552.001"],
	"cvssv4": "",
	"cwss": "CWSS:1.0/TI:H/AP:A/AL:M/IC:H/FC:H/RP:H/RL:H/AV:N/AS:L/IN:L/SC:N/CONF:N/T:A/P:M",
	"tags": ["secrets", "adp", "saas"],
}

_pattern := `(?i)adp[a-z0-9_]*(?:client)?[_-]?secret\s*[:=]\s*['"]?([A-Za-z0-9_\-]{24,})['"]?`
_keywords := ["adp", "secret"]

findings contains finding if {
	some path in object.keys(input.file_contents)
	not secrets.skip_path(path)
	lines := split(input.file_contents[path], "\n")
	some i, line in lines
	secrets.has_keyword(line, _keywords)
	m := regex.find_all_string_submatch_n(_pattern, line, 1)
	count(m) > 0
	token := m[0][1]
	not secrets.is_example_token(token)
	secrets.high_entropy(token, 4)
	finding := {
		"rule_id": metadata.id,
		"message": "ADP client secret found; rotate the client credentials in the ADP Developer portal",
		"artifact_uri": path,
		"severity": metadata.severity,
		"level": metadata.level,
		"start_line": i + 1,
		"snippet": secrets.redact(line),
	}
}
