package vulnetix.rules.vnx_sec_438

import rego.v1
import data.vulnetix.lib.secrets

# GENERATED by internal/sast/secretsgen from catalog.json — do not edit by hand.

metadata := {
	"id": "VNX-SEC-438",
	"name": "Pusher Channels app key",
	"description": "A Pusher Channels app key was found near a pusher assignment. It is a 20-character hex public identifier paired with the app secret.",
	"help_uri": "https://docs.cli.vulnetix.com/docs/sast-rules/secrets/communication/#vnx-sec-438",
	"languages": [],
	"severity": "medium",
	"level": "warning",
	"kind": "secrets",
	"cwe": [798],
	"capec": ["CAPEC-191"],
	"attack_technique": ["T1552.001"],
	"cvssv4": "",
	"cwss": "CWSS:1.0/TI:M/AP:A/AL:M/IC:M/FC:M/RP:H/RL:H/AV:N/AS:L/IN:L/SC:N/CONF:N/T:A/P:M",
	"tags": ["secrets", "pusher", "communication"],
}

_pattern := `(?i)pusher[a-z0-9_]*(?:app[_-]?key|key)[a-z0-9_]*\s*[:=]\s*['"]?([a-f0-9]{20})['"]?`
_keywords := ["pusher", "key"]

findings contains finding if {
	some path in object.keys(input.file_contents)
	not secrets.skip_path(path)
	lines := split(input.file_contents[path], "\n")
	some i, line in lines
	secrets.has_keyword(line, _keywords)
	m := regex.find_all_string_submatch_n(_pattern, line, 1)
	count(m) > 0
	token := m[0][1]
	not secrets.is_example_token(token)
	secrets.high_entropy(token, 3.5)
	finding := {
		"rule_id": metadata.id,
		"message": "Pusher Channels app key found; public alone, but confirm the paired app secret was not committed",
		"artifact_uri": path,
		"severity": metadata.severity,
		"level": metadata.level,
		"start_line": i + 1,
		"snippet": secrets.redact(line),
	}
}
