package vulnetix.rules.vnx_sec_649

import rego.v1
import data.vulnetix.lib.secrets

# GENERATED by internal/sast/secretsgen from catalog.json — do not edit by hand.

metadata := {
	"id": "VNX-SEC-649",
	"name": "PKCS12 keystore reference",
	"description": "A reference to a PKCS#12 keystore (.p12/.pfx) was found alongside a password. PKCS12 files bundle a private key and certificate chain and are frequently committed with the unlock password.",
	"help_uri": "https://docs.cli.vulnetix.com/docs/sast-rules/secrets/private-keys/#vnx-sec-649",
	"languages": [],
	"severity": "high",
	"level": "error",
	"kind": "secrets",
	"cwe": [798],
	"capec": ["CAPEC-191"],
	"attack_technique": ["T1552.004"],
	"cvssv4": "",
	"cwss": "CWSS:1.0/TI:H/AP:A/AL:M/IC:H/FC:H/RP:H/RL:H/AV:N/AS:L/IN:L/SC:N/CONF:N/T:A/P:M",
	"tags": ["secrets", "pkcs12", "private-keys"],
}

_pattern := `(?i)(?:p12|pkcs12|pfx)[_-]?(?:password|passphrase|pass)\s*[:=]\s*["']?([^\s"']{8,})["']?`
_keywords := ["p12", "pkcs12", "pfx", "keystore"]

findings contains finding if {
	some path in object.keys(input.file_contents)
	not secrets.skip_path(path)
	lines := split(input.file_contents[path], "\n")
	some i, line in lines
	secrets.has_keyword(line, _keywords)
	m := regex.find_all_string_submatch_n(_pattern, line, 1)
	count(m) > 0
	token := m[0][1]
	not secrets.is_example_token(token)
	secrets.high_entropy(token, 3)
	finding := {
		"rule_id": metadata.id,
		"message": "PKCS12 keystore password found; rotate the keystore password and regenerate the contained key pair if exposed",
		"artifact_uri": path,
		"severity": metadata.severity,
		"level": metadata.level,
		"start_line": i + 1,
		"snippet": secrets.redact(line),
	}
}
