package vulnetix.rules.vnx_sec_422

import rego.v1
import data.vulnetix.lib.secrets

# GENERATED by internal/sast/secretsgen from catalog.json — do not edit by hand.

metadata := {
	"id": "VNX-SEC-422",
	"name": "Microsoft Graph / Azure AD client secret",
	"description": "A Microsoft Graph / Azure AD application client secret was found near a graph or azure assignment. These secrets let an app authenticate to Microsoft Graph (Teams, Mail, Users) as itself.",
	"help_uri": "https://docs.cli.vulnetix.com/docs/sast-rules/secrets/communication/#vnx-sec-422",
	"languages": [],
	"severity": "critical",
	"level": "error",
	"kind": "secrets",
	"cwe": [798],
	"capec": ["CAPEC-191"],
	"attack_technique": ["T1552.001"],
	"cvssv4": "",
	"cwss": "CWSS:1.0/TI:H/AP:A/AL:H/IC:H/FC:H/RP:H/RL:H/AV:N/AS:L/IN:L/SC:N/CONF:N/T:A/P:H",
	"tags": ["secrets", "microsoft-graph", "communication"],
}

_pattern := `(?i)(?:graph|msgraph|azure|aad)[a-z0-9_]*(?:client[_-]?secret|secret)[a-z0-9_]*\s*[:=]\s*['"]?([A-Za-z0-9~._-]{34,44})['"]?`
_keywords := ["graph", "azure", "secret"]

findings contains finding if {
	some path in object.keys(input.file_contents)
	not secrets.skip_path(path)
	lines := split(input.file_contents[path], "\n")
	some i, line in lines
	secrets.has_keyword(line, _keywords)
	m := regex.find_all_string_submatch_n(_pattern, line, 1)
	count(m) > 0
	token := m[0][1]
	not secrets.is_example_token(token)
	secrets.high_entropy(token, 3.8)
	finding := {
		"rule_id": metadata.id,
		"message": "Microsoft Graph/Azure AD client secret found; delete it in the Azure portal under App registrations \u003e Certificates \u0026 secrets and create a new one",
		"artifact_uri": path,
		"severity": metadata.severity,
		"level": metadata.level,
		"start_line": i + 1,
		"snippet": secrets.redact(line),
	}
}
