package vulnetix.rules.vnx_sec_630

import rego.v1
import data.vulnetix.lib.secrets

# GENERATED by internal/sast/secretsgen from catalog.json — do not edit by hand.

metadata := {
	"id": "VNX-SEC-630",
	"name": "Snowflake account locator + region",
	"description": "A Snowflake account identifier assigned to a context keyword was found. While not secret alone, the account locator is paired with credentials to target a specific Snowflake account and aids attackers correlating leaked credentials.",
	"help_uri": "https://docs.cli.vulnetix.com/docs/sast-rules/secrets/database/#vnx-sec-630",
	"languages": [],
	"severity": "medium",
	"level": "warning",
	"kind": "secrets",
	"cwe": [798],
	"capec": ["CAPEC-191"],
	"attack_technique": ["T1552.001"],
	"cvssv4": "",
	"cwss": "CWSS:1.0/TI:M/AP:A/AL:M/IC:M/FC:M/RP:H/RL:H/AV:N/AS:L/IN:L/SC:N/CONF:N/T:A/P:M",
	"tags": ["secrets", "snowflake", "database"],
}

_pattern := `(?i)snowflake[a-z0-9_]*account\s*[:=]\s*['"]?([a-z0-9]{6,12}[.-](?:[a-z0-9-]+\.)*[a-z]{2,}-[a-z]+-[0-9]+(?:\.(?:aws|gcp|azure))?)['"]?`
_keywords := ["snowflake", "account"]

findings contains finding if {
	some path in object.keys(input.file_contents)
	not secrets.skip_path(path)
	lines := split(input.file_contents[path], "\n")
	some i, line in lines
	secrets.has_keyword(line, _keywords)
	m := regex.find_all_string_submatch_n(_pattern, line, 1)
	count(m) > 0
	token := m[0][1]
	not secrets.is_example_token(token)
	finding := {
		"rule_id": metadata.id,
		"message": "Snowflake account identifier found; ensure paired credentials (password, key pair or PAT) are rotated if exposure is suspected",
		"artifact_uri": path,
		"severity": metadata.severity,
		"level": metadata.level,
		"start_line": i + 1,
		"snippet": secrets.redact(line),
	}
}
