package vulnetix.rules.vnx_sec_825

import rego.v1
import data.vulnetix.lib.secrets

# GENERATED by internal/sast/secretsgen from catalog.json — do not edit by hand.

metadata := {
	"id": "VNX-SEC-825",
	"name": "Magento integration access token",
	"description": "A Magento (Adobe Commerce) integration access token was found. It authenticates REST/SOAP calls and grants access to the configured integration scopes including orders and customers.",
	"help_uri": "https://docs.cli.vulnetix.com/docs/sast-rules/secrets/saas/#vnx-sec-825",
	"languages": [],
	"severity": "critical",
	"level": "error",
	"kind": "secrets",
	"cwe": [798],
	"capec": ["CAPEC-191"],
	"attack_technique": ["T1552.001"],
	"cvssv4": "",
	"cwss": "CWSS:1.0/TI:H/AP:A/AL:H/IC:H/FC:H/RP:H/RL:H/AV:N/AS:L/IN:L/SC:N/CONF:N/T:A/P:H",
	"tags": ["secrets", "magento", "saas"],
}

_pattern := `(?i)magento[a-z0-9_]*(?:access[_-]?token|token)\s*[:=]\s*['"]?([a-z0-9]{32})['"]?`
_keywords := ["magento", "token"]

findings contains finding if {
	some path in object.keys(input.file_contents)
	not secrets.skip_path(path)
	lines := split(input.file_contents[path], "\n")
	some i, line in lines
	secrets.has_keyword(line, _keywords)
	m := regex.find_all_string_submatch_n(_pattern, line, 1)
	count(m) > 0
	token := m[0][1]
	not secrets.is_example_token(token)
	secrets.high_entropy(token, 3.5)
	finding := {
		"rule_id": metadata.id,
		"message": "Magento integration access token found; revoke the integration in System \u003e Integrations and recreate it",
		"artifact_uri": path,
		"severity": metadata.severity,
		"level": metadata.level,
		"start_line": i + 1,
		"snippet": secrets.redact(line),
	}
}
