package vulnetix.rules.vnx_sec_348

import rego.v1
import data.vulnetix.lib.secrets

# GENERATED by internal/sast/secretsgen from catalog.json — do not edit by hand.

metadata := {
	"id": "VNX-SEC-348",
	"name": "GoCardless live access token (live_)",
	"description": "A GoCardless live access token was found near a gocardless assignment using the live_ prefix. It authorizes live direct-debit mandate and payment operations.",
	"help_uri": "https://docs.cli.vulnetix.com/docs/sast-rules/secrets/payment/#vnx-sec-348",
	"languages": [],
	"severity": "critical",
	"level": "error",
	"kind": "secrets",
	"cwe": [798],
	"capec": ["CAPEC-191"],
	"attack_technique": ["T1552.001"],
	"cvssv4": "",
	"cwss": "CWSS:1.0/TI:H/AP:A/AL:H/IC:H/FC:H/RP:H/RL:H/AV:N/AS:L/IN:L/SC:N/CONF:N/T:A/P:H",
	"tags": ["secrets", "gocardless", "payment"],
}

_pattern := `(?i)gocardless[a-z0-9_]*\s*[:=]\s*['"]?(live_[A-Za-z0-9_=-]{40})['"]?`
_keywords := ["gocardless", "live_"]

findings contains finding if {
	some path in object.keys(input.file_contents)
	not secrets.skip_path(path)
	lines := split(input.file_contents[path], "\n")
	some i, line in lines
	secrets.has_keyword(line, _keywords)
	m := regex.find_all_string_submatch_n(_pattern, line, 1)
	count(m) > 0
	token := m[0][1]
	not secrets.is_example_token(token)
	secrets.high_entropy(token, 3.6)
	finding := {
		"rule_id": metadata.id,
		"message": "GoCardless live access token found; revoke it in the GoCardless Dashboard under Developers \u003e Access tokens",
		"artifact_uri": path,
		"severity": metadata.severity,
		"level": metadata.level,
		"start_line": i + 1,
		"snippet": secrets.redact(line),
	}
}
