package vulnetix.rules.vnx_sec_332

import rego.v1
import data.vulnetix.lib.secrets

# GENERATED by internal/sast/secretsgen from catalog.json — do not edit by hand.

metadata := {
	"id": "VNX-SEC-332",
	"name": "Adyen HMAC key",
	"description": "An Adyen HMAC key used to sign and verify webhook notifications was found near an adyen/hmac assignment. Exposure lets attackers forge notification signatures.",
	"help_uri": "https://docs.cli.vulnetix.com/docs/sast-rules/secrets/payment/#vnx-sec-332",
	"languages": [],
	"severity": "high",
	"level": "error",
	"kind": "secrets",
	"cwe": [798],
	"capec": ["CAPEC-191"],
	"attack_technique": ["T1552.001"],
	"cvssv4": "",
	"cwss": "CWSS:1.0/TI:H/AP:A/AL:M/IC:H/FC:H/RP:H/RL:H/AV:N/AS:L/IN:L/SC:N/CONF:N/T:A/P:M",
	"tags": ["secrets", "adyen", "payment"],
}

_pattern := `(?i)adyen[a-z0-9_]*hmac[a-z0-9_]*\s*[:=]\s*['"]?([A-F0-9]{64})['"]?`
_keywords := ["adyen", "hmac"]

findings contains finding if {
	some path in object.keys(input.file_contents)
	not secrets.skip_path(path)
	lines := split(input.file_contents[path], "\n")
	some i, line in lines
	secrets.has_keyword(line, _keywords)
	m := regex.find_all_string_submatch_n(_pattern, line, 1)
	count(m) > 0
	token := m[0][1]
	not secrets.is_example_token(token)
	secrets.high_entropy(token, 3.5)
	finding := {
		"rule_id": metadata.id,
		"message": "Adyen HMAC key found; regenerate the HMAC key for the affected webhook in the Adyen Customer Area",
		"artifact_uri": path,
		"severity": metadata.severity,
		"level": metadata.level,
		"start_line": i + 1,
		"snippet": secrets.redact(line),
	}
}
