package vulnetix.rules.vnx_sec_103

import rego.v1
import data.vulnetix.lib.secrets

# GENERATED by internal/sast/secretsgen from catalog.json — do not edit by hand.

metadata := {
	"id": "VNX-SEC-103",
	"name": "IBM Cloud IAM API key",
	"description": "An IBM Cloud IAM API key assigned to a context keyword was found. IBM Cloud IAM keys grant programmatic access to the account's services according to the key owner's IAM policies.",
	"help_uri": "https://docs.cli.vulnetix.com/docs/sast-rules/secrets/cloud/#vnx-sec-103",
	"languages": [],
	"severity": "critical",
	"level": "error",
	"kind": "secrets",
	"cwe": [798],
	"capec": ["CAPEC-191"],
	"attack_technique": ["T1552.001"],
	"cvssv4": "",
	"cwss": "CWSS:1.0/TI:H/AP:A/AL:H/IC:H/FC:H/RP:H/RL:H/AV:N/AS:L/IN:L/SC:N/CONF:N/T:A/P:H",
	"tags": ["secrets", "ibm", "cloud"],
}

_pattern := `(?i)(?:ibm[_-]?cloud|ibmcloud|iam)[a-z0-9_]*(?:api[_-]?key|apikey)[a-z0-9_]*\s*[:=]\s*['"]?([A-Za-z0-9_-]{44})['"]?`
_keywords := ["ibm", "iam", "apikey"]

findings contains finding if {
	some path in object.keys(input.file_contents)
	not secrets.skip_path(path)
	lines := split(input.file_contents[path], "\n")
	some i, line in lines
	secrets.has_keyword(line, _keywords)
	m := regex.find_all_string_submatch_n(_pattern, line, 1)
	count(m) > 0
	token := m[0][1]
	not secrets.is_example_token(token)
	secrets.high_entropy(token, 3.5)
	finding := {
		"rule_id": metadata.id,
		"message": "IBM Cloud IAM API key found; delete it in the IBM Cloud console under Manage \u003e Access (IAM) \u003e API keys and create a new one",
		"artifact_uri": path,
		"severity": metadata.severity,
		"level": metadata.level,
		"start_line": i + 1,
		"snippet": secrets.redact(line),
	}
}
