package vulnetix.rules.vnx_sec_247

import rego.v1
import data.vulnetix.lib.secrets

# GENERATED by internal/sast/secretsgen from catalog.json — do not edit by hand.

metadata := {
	"id": "VNX-SEC-247",
	"name": "Pulumi config passphrase",
	"description": "A Pulumi config passphrase (PULUMI_CONFIG_PASSPHRASE) used to encrypt stack secrets was found. It can decrypt secret config values in Pulumi state.",
	"help_uri": "https://docs.cli.vulnetix.com/docs/sast-rules/secrets/source-control/#vnx-sec-247",
	"languages": [],
	"severity": "high",
	"level": "error",
	"kind": "secrets",
	"cwe": [798],
	"capec": ["CAPEC-191"],
	"attack_technique": ["T1552.001"],
	"cvssv4": "",
	"cwss": "CWSS:1.0/TI:H/AP:A/AL:M/IC:H/FC:H/RP:H/RL:H/AV:N/AS:L/IN:L/SC:N/CONF:N/T:A/P:M",
	"tags": ["secrets", "pulumi", "source-control"],
}

_pattern := `(?i)pulumi[_-]?config[_-]?passphrase\s*[:=]\s*['"]?([^\s'"]{8,})['"]?`
_keywords := ["pulumi_config_passphrase"]

findings contains finding if {
	some path in object.keys(input.file_contents)
	not secrets.skip_path(path)
	lines := split(input.file_contents[path], "\n")
	some i, line in lines
	secrets.has_keyword(line, _keywords)
	m := regex.find_all_string_submatch_n(_pattern, line, 1)
	count(m) > 0
	token := m[0][1]
	not secrets.is_example_token(token)
	secrets.high_entropy(token, 3.2)
	finding := {
		"rule_id": metadata.id,
		"message": "Pulumi config passphrase found; rotate it and re-encrypt stack secrets with 'pulumi stack change-secrets-provider'",
		"artifact_uri": path,
		"severity": metadata.severity,
		"level": metadata.level,
		"start_line": i + 1,
		"snippet": secrets.redact(line),
	}
}
