package vulnetix.rules.vnx_sec_937

import rego.v1
import data.vulnetix.lib.secrets

# GENERATED by internal/sast/secretsgen from catalog.json — do not edit by hand.

metadata := {
	"id": "VNX-SEC-937",
	"name": "Twilio Super SIM / IoT API key (SK)",
	"description": "A Twilio API Key SID was found near a Super SIM / IoT context. Twilio API Keys begin with SK followed by 32 hex characters and, paired with their secret, authorize Super SIM fleet and IoT commands.",
	"help_uri": "https://docs.cli.vulnetix.com/docs/sast-rules/secrets/saas/#vnx-sec-937",
	"languages": [],
	"severity": "high",
	"level": "error",
	"kind": "secrets",
	"cwe": [798],
	"capec": ["CAPEC-191"],
	"attack_technique": ["T1552.001"],
	"cvssv4": "",
	"cwss": "CWSS:1.0/TI:H/AP:A/AL:M/IC:H/FC:H/RP:H/RL:H/AV:N/AS:L/IN:L/SC:N/CONF:N/T:A/P:M",
	"tags": ["secrets", "twiliosupersim", "saas"],
}

_pattern := `(?i)(?:supersim|super[_-]?sim|twilio[_-]?iot|iot)[a-z0-9_]*(?:api[_-]?key|apikey|sid|key)[a-z0-9_]*\s*[:=]\s*['"]?(SK[0-9a-f]{32})['"]?`
_keywords := ["supersim", "twilio iot"]

findings contains finding if {
	some path in object.keys(input.file_contents)
	not secrets.skip_path(path)
	lines := split(input.file_contents[path], "\n")
	some i, line in lines
	secrets.has_keyword(line, _keywords)
	m := regex.find_all_string_submatch_n(_pattern, line, 1)
	count(m) > 0
	token := m[0][1]
	not secrets.is_example_token(token)
	secrets.high_entropy(token, 3)
	finding := {
		"rule_id": metadata.id,
		"message": "Twilio Super SIM API key found; revoke the API Key in the Twilio console under Account \u003e API keys \u0026 tokens",
		"artifact_uri": path,
		"severity": metadata.severity,
		"level": metadata.level,
		"start_line": i + 1,
		"snippet": secrets.redact(line),
	}
}
