package vulnetix.rules.vnx_sec_652

import rego.v1
import data.vulnetix.lib.secrets

# GENERATED by internal/sast/secretsgen from catalog.json — do not edit by hand.

metadata := {
	"id": "VNX-SEC-652",
	"name": "Bitcoin WIF private key",
	"description": "A Bitcoin Wallet Import Format (WIF) private key was found. These Base58Check strings (51 chars starting 5, or 52 chars starting K/L on mainnet) directly control the spending of funds in a Bitcoin wallet.",
	"help_uri": "https://docs.cli.vulnetix.com/docs/sast-rules/secrets/crypto-blockchain/#vnx-sec-652",
	"languages": [],
	"severity": "critical",
	"level": "error",
	"kind": "secrets",
	"cwe": [798],
	"capec": ["CAPEC-191"],
	"attack_technique": ["T1552.001"],
	"cvssv4": "",
	"cwss": "CWSS:1.0/TI:H/AP:A/AL:H/IC:H/FC:H/RP:H/RL:H/AV:N/AS:L/IN:L/SC:N/CONF:N/T:A/P:H",
	"tags": ["secrets", "bitcoin", "crypto-blockchain"],
}

_pattern := `\b([5KL][1-9A-HJ-NP-Za-km-z]{50,51})\b`
_keywords := ["wif", "private key", "bitcoin", "btc"]

findings contains finding if {
	some path in object.keys(input.file_contents)
	not secrets.skip_path(path)
	lines := split(input.file_contents[path], "\n")
	some i, line in lines
	secrets.has_keyword(line, _keywords)
	m := regex.find_all_string_submatch_n(_pattern, line, 1)
	count(m) > 0
	token := m[0][1]
	not secrets.is_example_token(token)
	finding := {
		"rule_id": metadata.id,
		"message": "Bitcoin WIF private key found; immediately sweep funds to a new wallet as the exposed key cannot be rotated",
		"artifact_uri": path,
		"severity": metadata.severity,
		"level": metadata.level,
		"start_line": i + 1,
		"snippet": secrets.redact(line),
	}
}
