package vulnetix.rules.vnx_sec_167

import rego.v1
import data.vulnetix.lib.secrets

# GENERATED by internal/sast/secretsgen from catalog.json — do not edit by hand.

metadata := {
	"id": "VNX-SEC-167",
	"name": "Tencent Cloud SCF / API gateway secret (context)",
	"description": "A Tencent Cloud secret key under a generic tencent/qcloud secret context was found. It signs Tencent Cloud API and serverless requests granting account resource access.",
	"help_uri": "https://docs.cli.vulnetix.com/docs/sast-rules/secrets/cloud/#vnx-sec-167",
	"languages": [],
	"severity": "critical",
	"level": "error",
	"kind": "secrets",
	"cwe": [798],
	"capec": ["CAPEC-191"],
	"attack_technique": ["T1552.001"],
	"cvssv4": "",
	"cwss": "CWSS:1.0/TI:H/AP:A/AL:H/IC:H/FC:H/RP:H/RL:H/AV:N/AS:L/IN:L/SC:N/CONF:N/T:A/P:H",
	"tags": ["secrets", "tencent", "cloud"],
}

_pattern := `(?i)(?:secretkey|secret_key)\s*[:=]\s*['"]?([A-Za-z0-9]{32})['"]?[^\n]{0,40}(?:tencent|qcloud)`
_keywords := ["secretkey", "tencent", "qcloud"]

findings contains finding if {
	some path in object.keys(input.file_contents)
	not secrets.skip_path(path)
	lines := split(input.file_contents[path], "\n")
	some i, line in lines
	secrets.has_keyword(line, _keywords)
	m := regex.find_all_string_submatch_n(_pattern, line, 1)
	count(m) > 0
	token := m[0][1]
	not secrets.is_example_token(token)
	secrets.high_entropy(token, 3.5)
	finding := {
		"rule_id": metadata.id,
		"message": "Tencent Cloud secret key found; disable the API key pair in the Tencent Cloud CAM console and rotate",
		"artifact_uri": path,
		"severity": metadata.severity,
		"level": metadata.level,
		"start_line": i + 1,
		"snippet": secrets.redact(line),
	}
}
