package vulnetix.rules.vnx_sec_101

import rego.v1
import data.vulnetix.lib.secrets

# GENERATED by internal/sast/secretsgen from catalog.json — do not edit by hand.

metadata := {
	"id": "VNX-SEC-101",
	"name": "Oracle Cloud (OCI) API private key",
	"description": "An Oracle Cloud Infrastructure API signing private key (PEM RSA private key paired with an OCI user) was found. It authenticates as the OCI user and grants API access to all permitted tenancy resources.",
	"help_uri": "https://docs.cli.vulnetix.com/docs/sast-rules/secrets/cloud/#vnx-sec-101",
	"languages": [],
	"severity": "critical",
	"level": "error",
	"kind": "secrets",
	"cwe": [798],
	"capec": ["CAPEC-191"],
	"attack_technique": ["T1552.004"],
	"cvssv4": "",
	"cwss": "CWSS:1.0/TI:H/AP:A/AL:H/IC:H/FC:H/RP:H/RL:H/AV:N/AS:L/IN:L/SC:N/CONF:N/T:A/P:H",
	"tags": ["secrets", "oracle", "cloud"],
}

_pattern := `(-----BEGIN RSA PRIVATE KEY-----[\s\S]{64,}?-----END RSA PRIVATE KEY-----)`
_keywords := ["-----begin rsa private key-----"]

findings contains finding if {
	some path in object.keys(input.file_contents)
	not secrets.skip_path(path)
	lines := split(input.file_contents[path], "\n")
	some i, line in lines
	secrets.has_keyword(line, _keywords)
	m := regex.find_all_string_submatch_n(_pattern, line, 1)
	count(m) > 0
	token := m[0][1]
	not secrets.is_example_token(token)
	finding := {
		"rule_id": metadata.id,
		"message": "Oracle Cloud API signing key found; delete the API key under the OCI user's API Keys and upload a freshly generated key pair",
		"artifact_uri": path,
		"severity": metadata.severity,
		"level": metadata.level,
		"start_line": i + 1,
		"snippet": secrets.redact(line),
	}
}
