package vulnetix.rules.vnx_sec_934

import rego.v1
import data.vulnetix.lib.secrets

# GENERATED by internal/sast/secretsgen from catalog.json — do not edit by hand.

metadata := {
	"id": "VNX-SEC-934",
	"name": "Helium API key",
	"description": "A Helium console/network API key was found near a helium assignment. It is a high-entropy base64/URL-safe token authorizing device and integration management on the Helium IoT network.",
	"help_uri": "https://docs.cli.vulnetix.com/docs/sast-rules/secrets/saas/#vnx-sec-934",
	"languages": [],
	"severity": "high",
	"level": "error",
	"kind": "secrets",
	"cwe": [798],
	"capec": ["CAPEC-191"],
	"attack_technique": ["T1552.001"],
	"cvssv4": "",
	"cwss": "CWSS:1.0/TI:H/AP:A/AL:M/IC:H/FC:H/RP:H/RL:H/AV:N/AS:L/IN:L/SC:N/CONF:N/T:A/P:M",
	"tags": ["secrets", "helium", "saas"],
}

_pattern := `(?i)helium[a-z0-9_]*(?:api[_-]?key|apikey|token|key)[a-z0-9_]*\s*[:=]\s*['"]?([A-Za-z0-9_-]{40,}={0,2})['"]?`
_keywords := ["helium"]

findings contains finding if {
	some path in object.keys(input.file_contents)
	not secrets.skip_path(path)
	lines := split(input.file_contents[path], "\n")
	some i, line in lines
	secrets.has_keyword(line, _keywords)
	m := regex.find_all_string_submatch_n(_pattern, line, 1)
	count(m) > 0
	token := m[0][1]
	not secrets.is_example_token(token)
	secrets.high_entropy(token, 3.7)
	finding := {
		"rule_id": metadata.id,
		"message": "Helium API key found; revoke it in the Helium Console under Organization \u003e API Keys",
		"artifact_uri": path,
		"severity": metadata.severity,
		"level": metadata.level,
		"start_line": i + 1,
		"snippet": secrets.redact(line),
	}
}
