package vulnetix.rules.vnx_sec_905

import rego.v1
import data.vulnetix.lib.secrets

# GENERATED by internal/sast/secretsgen from catalog.json — do not edit by hand.

metadata := {
	"id": "VNX-SEC-905",
	"name": "Google Maps server API key (context)",
	"description": "A Google Maps Platform API key was found assigned to a maps/server key variable. Server-side keys (AIza...) authorize geocoding, places, and routes APIs and allow billed usage if leaked.",
	"help_uri": "https://docs.cli.vulnetix.com/docs/sast-rules/secrets/saas/#vnx-sec-905",
	"languages": [],
	"severity": "high",
	"level": "error",
	"kind": "secrets",
	"cwe": [798],
	"capec": ["CAPEC-191"],
	"attack_technique": ["T1552.001"],
	"cvssv4": "",
	"cwss": "CWSS:1.0/TI:H/AP:A/AL:M/IC:H/FC:H/RP:H/RL:H/AV:N/AS:L/IN:L/SC:N/CONF:N/T:A/P:M",
	"tags": ["secrets", "googlemaps", "saas"],
}

_pattern := `(?i)(?:google[_-]?maps|maps[_-]?api|gmaps|geocod)[a-z0-9_]*(?:api[_-]?key|apikey|server[_-]?key|key)[a-z0-9_]*\s*[:=]\s*['"]?(AIza[0-9A-Za-z_-]{35})['"]?`
_keywords := ["google", "maps"]

findings contains finding if {
	some path in object.keys(input.file_contents)
	not secrets.skip_path(path)
	lines := split(input.file_contents[path], "\n")
	some i, line in lines
	secrets.has_keyword(line, _keywords)
	m := regex.find_all_string_submatch_n(_pattern, line, 1)
	count(m) > 0
	token := m[0][1]
	not secrets.is_example_token(token)
	secrets.high_entropy(token, 3.5)
	finding := {
		"rule_id": metadata.id,
		"message": "Google Maps server API key found; restrict or rotate it in Google Cloud Console under APIs \u0026 Services \u003e Credentials and apply API/IP restrictions",
		"artifact_uri": path,
		"severity": metadata.severity,
		"level": metadata.level,
		"start_line": i + 1,
		"snippet": secrets.redact(line),
	}
}
