package vulnetix.rules.vnx_sec_110

import rego.v1
import data.vulnetix.lib.secrets

# GENERATED by internal/sast/secretsgen from catalog.json — do not edit by hand.

metadata := {
	"id": "VNX-SEC-110",
	"name": "Hetzner Cloud API token",
	"description": "A Hetzner Cloud API token assigned to a context keyword was found. Hetzner Cloud tokens grant full read/write access to the project's servers, volumes, networks and firewalls.",
	"help_uri": "https://docs.cli.vulnetix.com/docs/sast-rules/secrets/cloud/#vnx-sec-110",
	"languages": [],
	"severity": "critical",
	"level": "error",
	"kind": "secrets",
	"cwe": [798],
	"capec": ["CAPEC-191"],
	"attack_technique": ["T1552.001"],
	"cvssv4": "",
	"cwss": "CWSS:1.0/TI:H/AP:A/AL:H/IC:H/FC:H/RP:H/RL:H/AV:N/AS:L/IN:L/SC:N/CONF:N/T:A/P:H",
	"tags": ["secrets", "hetzner", "cloud"],
}

_pattern := `(?i)(?:hetzner|hcloud)[a-z0-9_]*(?:api[_-]?token|token)\s*[:=]\s*['"]?([A-Za-z0-9]{64})['"]?`
_keywords := ["hetzner", "hcloud", "token"]

findings contains finding if {
	some path in object.keys(input.file_contents)
	not secrets.skip_path(path)
	lines := split(input.file_contents[path], "\n")
	some i, line in lines
	secrets.has_keyword(line, _keywords)
	m := regex.find_all_string_submatch_n(_pattern, line, 1)
	count(m) > 0
	token := m[0][1]
	not secrets.is_example_token(token)
	secrets.high_entropy(token, 3.5)
	finding := {
		"rule_id": metadata.id,
		"message": "Hetzner Cloud API token found; revoke it in the Hetzner Cloud console under the project's Security \u003e API tokens and create a new one",
		"artifact_uri": path,
		"severity": metadata.severity,
		"level": metadata.level,
		"start_line": i + 1,
		"snippet": secrets.redact(line),
	}
}
