package vulnetix.rules.vnx_sec_908

import rego.v1
import data.vulnetix.lib.secrets

# GENERATED by internal/sast/secretsgen from catalog.json — do not edit by hand.

metadata := {
	"id": "VNX-SEC-908",
	"name": "AccuWeather API key",
	"description": "An AccuWeather API key was found near an accuweather assignment. It is a high-entropy URL-safe string authorizing locations and forecast API requests.",
	"help_uri": "https://docs.cli.vulnetix.com/docs/sast-rules/secrets/saas/#vnx-sec-908",
	"languages": [],
	"severity": "medium",
	"level": "warning",
	"kind": "secrets",
	"cwe": [798],
	"capec": ["CAPEC-191"],
	"attack_technique": ["T1552.001"],
	"cvssv4": "",
	"cwss": "CWSS:1.0/TI:M/AP:A/AL:M/IC:M/FC:M/RP:H/RL:H/AV:N/AS:L/IN:L/SC:N/CONF:N/T:A/P:M",
	"tags": ["secrets", "accuweather", "saas"],
}

_pattern := `(?i)accuweather[a-z0-9_]*(?:api[_-]?key|apikey|key)[a-z0-9_]*\s*[:=]\s*['"]?([A-Za-z0-9%]{32,40})['"]?`
_keywords := ["accuweather"]

findings contains finding if {
	some path in object.keys(input.file_contents)
	not secrets.skip_path(path)
	lines := split(input.file_contents[path], "\n")
	some i, line in lines
	secrets.has_keyword(line, _keywords)
	m := regex.find_all_string_submatch_n(_pattern, line, 1)
	count(m) > 0
	token := m[0][1]
	not secrets.is_example_token(token)
	secrets.high_entropy(token, 3.6)
	finding := {
		"rule_id": metadata.id,
		"message": "AccuWeather API key found; revoke it in the AccuWeather Developer Portal under My Apps",
		"artifact_uri": path,
		"severity": metadata.severity,
		"level": metadata.level,
		"start_line": i + 1,
		"snippet": secrets.redact(line),
	}
}
