package vulnetix.rules.vnx_sec_579

import rego.v1
import data.vulnetix.lib.secrets

# GENERATED by internal/sast/secretsgen from catalog.json — do not edit by hand.

metadata := {
	"id": "VNX-SEC-579",
	"name": "Confluent Cloud API key",
	"description": "A Confluent Cloud / Kafka API key (16-char uppercase key) assigned to a context keyword was found. Paired with its secret it authenticates to Confluent Cloud clusters and the Kafka API.",
	"help_uri": "https://docs.cli.vulnetix.com/docs/sast-rules/secrets/database/#vnx-sec-579",
	"languages": [],
	"severity": "high",
	"level": "error",
	"kind": "secrets",
	"cwe": [798],
	"capec": ["CAPEC-191"],
	"attack_technique": ["T1552.001"],
	"cvssv4": "",
	"cwss": "CWSS:1.0/TI:H/AP:A/AL:M/IC:H/FC:H/RP:H/RL:H/AV:N/AS:L/IN:L/SC:N/CONF:N/T:A/P:M",
	"tags": ["secrets", "confluent", "database"],
}

_pattern := `(?i)confluent[a-z0-9_]*(?:api[_-]?key|key)\s*[:=]\s*['"]?([A-Z0-9]{16})['"]?`
_keywords := ["confluent"]

findings contains finding if {
	some path in object.keys(input.file_contents)
	not secrets.skip_path(path)
	lines := split(input.file_contents[path], "\n")
	some i, line in lines
	secrets.has_keyword(line, _keywords)
	m := regex.find_all_string_submatch_n(_pattern, line, 1)
	count(m) > 0
	token := m[0][1]
	not secrets.is_example_token(token)
	secrets.high_entropy(token, 3)
	finding := {
		"rule_id": metadata.id,
		"message": "Confluent Cloud API key found; delete the API key in the Confluent Cloud console and create a new key/secret pair",
		"artifact_uri": path,
		"severity": metadata.severity,
		"level": metadata.level,
		"start_line": i + 1,
		"snippet": secrets.redact(line),
	}
}
