package vulnetix.rules.vnx_sec_327

import rego.v1
import data.vulnetix.lib.secrets

# GENERATED by internal/sast/secretsgen from catalog.json — do not edit by hand.

metadata := {
	"id": "VNX-SEC-327",
	"name": "PayPal/Braintree client id",
	"description": "A PayPal or Braintree REST client id was found. Client ids are not secret on their own but are paired with a client secret; their presence flags PayPal integration code for review.",
	"help_uri": "https://docs.cli.vulnetix.com/docs/sast-rules/secrets/payment/#vnx-sec-327",
	"languages": [],
	"severity": "medium",
	"level": "warning",
	"kind": "secrets",
	"cwe": [798],
	"capec": ["CAPEC-191"],
	"attack_technique": ["T1552.001"],
	"cvssv4": "",
	"cwss": "CWSS:1.0/TI:M/AP:A/AL:M/IC:M/FC:M/RP:H/RL:H/AV:N/AS:L/IN:L/SC:N/CONF:N/T:A/P:M",
	"tags": ["secrets", "paypal", "payment"],
}

_pattern := `(?i)paypal[a-z0-9_]*client_id[a-z0-9_]*\s*[:=]\s*['"]?(A[A-Za-z0-9_-]{79})['"]?`
_keywords := ["paypal", "client_id"]

findings contains finding if {
	some path in object.keys(input.file_contents)
	not secrets.skip_path(path)
	lines := split(input.file_contents[path], "\n")
	some i, line in lines
	secrets.has_keyword(line, _keywords)
	m := regex.find_all_string_submatch_n(_pattern, line, 1)
	count(m) > 0
	token := m[0][1]
	not secrets.is_example_token(token)
	secrets.high_entropy(token, 3.8)
	finding := {
		"rule_id": metadata.id,
		"message": "PayPal client id found; not secret alone, but verify the paired client secret was not committed",
		"artifact_uri": path,
		"severity": metadata.severity,
		"level": metadata.level,
		"start_line": i + 1,
		"snippet": secrets.redact(line),
	}
}
