package vulnetix.rules.vnx_sec_176

import rego.v1
import data.vulnetix.lib.secrets

# GENERATED by internal/sast/secretsgen from catalog.json — do not edit by hand.

metadata := {
	"id": "VNX-SEC-176",
	"name": "Oracle Cloud (OCI) config fingerprint+key context",
	"description": "An OCI config fingerprint paired with key context was found. The fingerprint identifies the API signing key uploaded to the OCI user; its exposure alongside the private key compromises the user.",
	"help_uri": "https://docs.cli.vulnetix.com/docs/sast-rules/secrets/cloud/#vnx-sec-176",
	"languages": [],
	"severity": "medium",
	"level": "warning",
	"kind": "secrets",
	"cwe": [798],
	"capec": ["CAPEC-191"],
	"attack_technique": ["T1552.001"],
	"cvssv4": "",
	"cwss": "CWSS:1.0/TI:M/AP:A/AL:M/IC:M/FC:M/RP:H/RL:H/AV:N/AS:L/IN:L/SC:N/CONF:N/T:A/P:M",
	"tags": ["secrets", "oracle", "cloud"],
}

_pattern := `(?i)(?:oci|oracle)[a-z0-9_]*fingerprint\s*[:=]\s*['"]?((?:[0-9a-f]{2}:){15}[0-9a-f]{2})['"]?`
_keywords := ["oci", "oracle", "fingerprint"]

findings contains finding if {
	some path in object.keys(input.file_contents)
	not secrets.skip_path(path)
	lines := split(input.file_contents[path], "\n")
	some i, line in lines
	secrets.has_keyword(line, _keywords)
	m := regex.find_all_string_submatch_n(_pattern, line, 1)
	count(m) > 0
	token := m[0][1]
	not secrets.is_example_token(token)
	finding := {
		"rule_id": metadata.id,
		"message": "OCI API key fingerprint found; ensure the associated private key is not committed and rotate the OCI API key if so",
		"artifact_uri": path,
		"severity": metadata.severity,
		"level": metadata.level,
		"start_line": i + 1,
		"snippet": secrets.redact(line),
	}
}
