name: 'Vulnetix CLI Action'
description: 'GitHub Action that provides the Vulnetix CLI utility for vulnerability management'
author: 'Vulnetix'
branding:
  icon: 'shield'
  color: 'red'

inputs:
  org-id:
    description: 'Organization ID (UUID) for Vulnetix operations'
    required: true
  version:
    description: 'Version of Vulnetix CLI to use'
    required: false
    default: 'latest'
  task:
    description: 'Task to perform: info, upload'
    required: false
    default: 'info'
  api-key:
    description: 'Direct API Key for Vulnetix authentication (hex digest)'
    required: false
  upload-file:
    description: 'Path to artifact file to upload (used with task: upload)'
    required: false
  upload-format:
    description: 'Override auto-detected artifact format (cyclonedx, spdx, sarif, openvex, csaf_vex)'
    required: false
outputs:
  result:
    description: 'Result of the Vulnetix CLI execution'
    value: ${{ steps.vulnetix-run.outputs.result }}
  summary:
    description: 'Summary of vulnerabilities processed'
    value: ${{ steps.vulnetix-run.outputs.summary }}
  upload-uuid:
    description: 'Pipeline UUID of the uploaded artifact (when task is upload)'
    value: ${{ steps.vulnetix-run.outputs.upload-uuid }}

runs:
  using: 'composite'
  steps:
    - name: Setup Vulnetix CLI
      shell: bash
      run: |
        echo "Setting up Vulnetix CLI..."

        # Ensure Go is available (install if not present)
        if ! command -v go &> /dev/null; then
          echo "Go not found, installing via go install is not possible."
          echo "Please add actions/setup-go to your workflow before this action."
          exit 1
        fi

        # Build from source using the action's own repository
        ACTION_DIR="${{ github.action_path }}"
        cd "$ACTION_DIR"

        mkdir -p "$HOME/bin"
        go build -ldflags "-s -w -X github.com/vulnetix/cli/cmd.version=${{ inputs.version }}" -o "$HOME/bin/vulnetix" .

        echo "$HOME/bin" >> $GITHUB_PATH

        echo "Vulnetix CLI setup complete ($(go version))"

    - name: Authenticate with Vulnetix
      if: inputs.api-key != ''
      shell: bash
      run: |
        vulnetix auth login \
          --method apikey \
          --org-id '${{ inputs.org-id }}' \
          --secret '${{ inputs.api-key }}' \
          --store project

    - name: Verify Vulnetix Authentication
      if: inputs.api-key != ''
      shell: bash
      run: |
        vulnetix auth verify

    - name: Run Vulnetix CLI
      id: vulnetix-run
      shell: bash
      run: |
        echo "Running Vulnetix CLI with org-id: ${{ inputs.org-id }}"

        # Handle upload task separately
        if [ "${{ inputs.task }}" = "upload" ]; then
          UPLOAD_ARGS="upload --file '${{ inputs.upload-file }}' --org-id '${{ inputs.org-id }}' --json"

          if [ -n "${{ inputs.upload-format }}" ]; then
            UPLOAD_ARGS="$UPLOAD_ARGS --format '${{ inputs.upload-format }}'"
          fi

          RESULT=$(eval "vulnetix $UPLOAD_ARGS")
          echo "$RESULT"

          # Extract pipeline ID for output
          PIPELINE_ID=$(echo "$RESULT" | jq -r '.pipelineRecord.uuid // empty' 2>/dev/null || true)
          if [ -n "$PIPELINE_ID" ]; then
            echo "upload-uuid=$PIPELINE_ID" >> $GITHUB_OUTPUT
          fi

          echo "result=success" >> $GITHUB_OUTPUT
          echo "summary=Artifact uploaded successfully" >> $GITHUB_OUTPUT
          exit 0
        fi

        # Default task: run info healthcheck
        vulnetix

        # Set outputs (these would be set by the actual CLI)
        echo "result=success" >> $GITHUB_OUTPUT
        echo "summary=Vulnerability analysis completed" >> $GITHUB_OUTPUT
