package bom

import (
	"sort"
	"strings"

	"github.com/vulnetix/cli/v3/internal/cdx"
	"github.com/vulnetix/cli/v3/internal/versions"
)

// diff.go compares two SBOMs.
//
// Matching follows the same cascade internal/cdx/merge.go already proved on the
// write side — purl, then bom-ref, then name@version — because two documents
// generated by different tools from the same tree agree on purls long before
// they agree on refs. Version movement is compared through internal/versions
// rather than by string inequality, so "1.2.10 → 1.2.9" reads as the downgrade
// it is, which is the change most worth catching in a release review.

// ChangeKind classifies a component-level change.
type ChangeKind string

const (
	ChangeAdded      ChangeKind = "added"
	ChangeRemoved    ChangeKind = "removed"
	ChangeUpgraded   ChangeKind = "upgraded"
	ChangeDowngraded ChangeKind = "downgraded"
	// ChangeVersionChanged is a version that moved in a way semver could not
	// order — a git sha replacing a tag, a distro epoch, a date stamp. Reported
	// as movement without a direction rather than guessed at.
	ChangeVersionChanged ChangeKind = "version-changed"
	ChangeLicense        ChangeKind = "license-changed"
)

// ComponentChange is one component-level difference.
type ComponentChange struct {
	Kind ChangeKind `json:"kind"`
	// Name and Purl identify the component; Purl is empty when neither side had one.
	Name string `json:"name"`
	Purl string `json:"purl,omitempty"`
	// FromVersion and ToVersion are empty for the side that does not exist.
	FromVersion string `json:"fromVersion,omitempty"`
	ToVersion   string `json:"toVersion,omitempty"`
	// FromLicense and ToLicense are rendered licence expressions.
	FromLicense string `json:"fromLicense,omitempty"`
	ToLicense   string `json:"toLicense,omitempty"`
	// Direct reports whether the component is a direct dependency of the
	// subject on whichever side it exists. Nil when there is no dependency
	// graph to answer from — an unmeasurable fact stays null, never false.
	Direct *bool `json:"direct,omitempty"`
}

// VulnChange is one vulnerability-level difference.
type VulnChange struct {
	Kind ChangeKind `json:"kind"` // ChangeAdded or ChangeRemoved
	ID   string     `json:"id"`
	// Severity is the highest severity rating carried on the entry, or "".
	Severity string `json:"severity,omitempty"`
	// Affects lists the component refs the entry points at.
	Affects []string `json:"affects,omitempty"`
}

// DiffSummary is the headline count set.
type DiffSummary struct {
	Added           int `json:"added"`
	Removed         int `json:"removed"`
	Upgraded        int `json:"upgraded"`
	Downgraded      int `json:"downgraded"`
	VersionChanged  int `json:"versionChanged"`
	LicenseChanged  int `json:"licenseChanged"`
	VulnsAdded      int `json:"vulnsAdded"`
	VulnsRemoved    int `json:"vulnsRemoved"`
	FromComponents  int `json:"fromComponents"`
	ToComponents    int `json:"toComponents"`
	GraphEdgesAdded int `json:"graphEdgesAdded"`
	GraphEdgesGone  int `json:"graphEdgesRemoved"`
}

// Total is the number of component-level changes.
func (s DiffSummary) Total() int {
	return s.Added + s.Removed + s.Upgraded + s.Downgraded + s.VersionChanged + s.LicenseChanged
}

// Diff is the full comparison of two documents.
type Diff struct {
	From       SourceInfo        `json:"from"`
	To         SourceInfo        `json:"to"`
	Identical  bool              `json:"identical"`
	Summary    DiffSummary       `json:"summary"`
	Components []ComponentChange `json:"components,omitempty"`
	Vulns      []VulnChange      `json:"vulnerabilities,omitempty"`
}

// CompareDocuments diffs two parsed documents.
func CompareDocuments(from, to *Document) *Diff {
	d := &Diff{From: from.Source, To: to.Source}
	// Byte-identical inputs cannot differ, and saying so plainly is more useful
	// than an empty change list the reader has to interpret.
	if from.Source.Digest != "" && from.Source.Digest == to.Source.Digest {
		d.Identical = true
	}

	fromComps := indexComponents(from.BOM)
	toComps := indexComponents(to.BOM)
	fromDirect := directRefs(from.BOM)
	toDirect := directRefs(to.BOM)

	d.Summary.FromComponents = len(fromComps.order)
	d.Summary.ToComponents = len(toComps.order)

	matchedTo := make(map[string]bool, len(toComps.order))

	for _, key := range fromComps.order {
		fc := fromComps.byKey[key]
		tc, tkey := toComps.lookup(fc)
		if tc == nil {
			direct := directness(fromDirect, fc)
			d.Components = append(d.Components, ComponentChange{
				Kind:        ChangeRemoved,
				Name:        fc.Name,
				Purl:        fc.Purl,
				FromVersion: fc.Version,
				FromLicense: renderLicenses(fc),
				Direct:      direct,
			})
			d.Summary.Removed++
			continue
		}
		matchedTo[tkey] = true

		if fc.Version != tc.Version {
			kind := versionChangeKind(fc.Version, tc.Version)
			d.Components = append(d.Components, ComponentChange{
				Kind:        kind,
				Name:        preferName(tc.Name, fc.Name),
				Purl:        preferName(tc.Purl, fc.Purl),
				FromVersion: fc.Version,
				ToVersion:   tc.Version,
				Direct:      directness(toDirect, tc),
			})
			switch kind {
			case ChangeUpgraded:
				d.Summary.Upgraded++
			case ChangeDowngraded:
				d.Summary.Downgraded++
			default:
				d.Summary.VersionChanged++
			}
		}

		if fl, tl := renderLicenses(fc), renderLicenses(tc); fl != tl {
			d.Components = append(d.Components, ComponentChange{
				Kind:        ChangeLicense,
				Name:        preferName(tc.Name, fc.Name),
				Purl:        preferName(tc.Purl, fc.Purl),
				FromVersion: fc.Version,
				ToVersion:   tc.Version,
				FromLicense: fl,
				ToLicense:   tl,
				Direct:      directness(toDirect, tc),
			})
			d.Summary.LicenseChanged++
		}
	}

	for _, key := range toComps.order {
		if matchedTo[key] {
			continue
		}
		tc := toComps.byKey[key]
		// A component the `from` side matched under a different key is not new.
		if c, _ := fromComps.lookup(tc); c != nil {
			continue
		}
		d.Components = append(d.Components, ComponentChange{
			Kind:      ChangeAdded,
			Name:      tc.Name,
			Purl:      tc.Purl,
			ToVersion: tc.Version,
			ToLicense: renderLicenses(tc),
			Direct:    directness(toDirect, tc),
		})
		d.Summary.Added++
	}

	d.Vulns = diffVulns(from.BOM, to.BOM, &d.Summary)
	d.Summary.GraphEdgesAdded, d.Summary.GraphEdgesGone = diffGraph(from.BOM, to.BOM)

	sortChanges(d.Components)
	return d
}

// componentIndex holds a document's components under every key they can be
// matched by, so lookup can try the cascade without rebuilding maps.
type componentIndex struct {
	order  []string // canonical keys, in document order
	byKey  map[string]*cdx.Component
	byPurl map[string]string // purl → canonical key
	byRef  map[string]string // bom-ref → canonical key
	byNV   map[string]string // name@version → canonical key
	byName map[string]string // name → canonical key (only when unambiguous)
}

// lookup finds the counterpart of c, returning it and its canonical key.
//
// The cascade goes purl → bom-ref → name@version → name. The final
// name-only step is what lets a version change be seen as a change rather than
// as an unrelated add and remove, and it is restricted to names that appear
// exactly once so it can never pair the wrong two components.
func (idx *componentIndex) lookup(c *cdx.Component) (*cdx.Component, string) {
	try := func(m map[string]string, k string) (*cdx.Component, string) {
		if k == "" {
			return nil, ""
		}
		if key, ok := m[k]; ok {
			return idx.byKey[key], key
		}
		return nil, ""
	}
	if got, key := try(idx.byPurl, purlWithoutVersion(c.Purl)); got != nil {
		return got, key
	}
	if got, key := try(idx.byRef, c.BOMRef); got != nil {
		return got, key
	}
	if got, key := try(idx.byNV, nameVersion(c)); got != nil {
		return got, key
	}
	return try(idx.byName, c.Name)
}

// indexComponents builds the match index for a document.
func indexComponents(bom *cdx.BOM) *componentIndex {
	idx := &componentIndex{
		byKey:  map[string]*cdx.Component{},
		byPurl: map[string]string{},
		byRef:  map[string]string{},
		byNV:   map[string]string{},
		byName: map[string]string{},
	}
	if bom == nil {
		return idx
	}
	nameCounts := map[string]int{}
	for i := range bom.Components {
		nameCounts[bom.Components[i].Name]++
	}
	for i := range bom.Components {
		c := &bom.Components[i]
		key := canonicalKey(c)
		if _, dup := idx.byKey[key]; dup {
			continue
		}
		idx.byKey[key] = c
		idx.order = append(idx.order, key)

		if pu := purlWithoutVersion(c.Purl); pu != "" {
			if _, ok := idx.byPurl[pu]; !ok {
				idx.byPurl[pu] = key
			}
		}
		if c.BOMRef != "" {
			if _, ok := idx.byRef[c.BOMRef]; !ok {
				idx.byRef[c.BOMRef] = key
			}
		}
		if nv := nameVersion(c); nv != "" {
			if _, ok := idx.byNV[nv]; !ok {
				idx.byNV[nv] = key
			}
		}
		if c.Name != "" && nameCounts[c.Name] == 1 {
			idx.byName[c.Name] = key
		}
	}
	return idx
}

// canonicalKey is a component's stable identity within one document.
func canonicalKey(c *cdx.Component) string {
	switch {
	case c.Purl != "":
		return "purl:" + c.Purl
	case c.BOMRef != "":
		return "ref:" + c.BOMRef
	default:
		return "nv:" + nameVersion(c)
	}
}

// purlWithoutVersion strips the version, qualifiers and subpath from a purl.
//
// Matching on the versionless purl is the whole point: `pkg:npm/lodash@4.17.20`
// and `pkg:npm/lodash@4.17.21` are the same dependency at two versions, which
// is a version change, not a remove plus an add.
//
// The version separator is the LAST '@' after the final '/', not the first '@'
// in the string. The spec says a namespace's '@' must be percent-encoded, but
// scoped npm packages are routinely emitted raw as `pkg:npm/@scope/pkg@1.0.0`,
// and splitting on the first '@' there yields `pkg:npm/` — a key every scoped
// package in the document would collide on, silently pairing unrelated
// components in a diff.
func purlWithoutVersion(p string) string {
	if p == "" {
		return ""
	}
	if i := strings.IndexAny(p, "?#"); i >= 0 {
		p = p[:i]
	}
	at := strings.LastIndex(p, "@")
	if at > strings.LastIndex(p, "/") {
		return p[:at]
	}
	return p
}

// nameVersion renders "name@version", or just the name when unversioned.
func nameVersion(c *cdx.Component) string {
	if c.Name == "" {
		return ""
	}
	if c.Version == "" {
		return c.Name
	}
	return c.Name + "@" + c.Version
}

// versionChangeKind orders two versions, falling back to an undirected change.
func versionChangeKind(from, to string) ChangeKind {
	fv, ferr := versions.Parse(from)
	tv, terr := versions.Parse(to)
	if ferr != nil || terr != nil {
		return ChangeVersionChanged
	}
	switch versions.Compare(fv, tv) {
	case -1:
		return ChangeUpgraded
	case 1:
		return ChangeDowngraded
	default:
		// Parsed equal but spelled differently ("1.2.0" vs "v1.2.0"). Real
		// movement in the document, no movement in the dependency.
		return ChangeVersionChanged
	}
}

// renderLicenses renders a component's licences as one comparable string.
func renderLicenses(c *cdx.Component) string {
	if c == nil || len(c.Licenses) == 0 {
		return ""
	}
	parts := make([]string, 0, len(c.Licenses))
	for _, lc := range c.Licenses {
		switch {
		case lc.Expression != "":
			parts = append(parts, lc.Expression)
		case lc.License != nil && lc.License.ID != "":
			parts = append(parts, lc.License.ID)
		case lc.License != nil && lc.License.Name != "":
			parts = append(parts, lc.License.Name)
		}
	}
	// Sorted so that a reordering of the same licence set is not a change.
	sort.Strings(parts)
	return strings.Join(parts, ", ")
}

// directRefs returns the set of bom-refs the subject depends on directly.
//
// Empty when the document has no dependency graph or no subject, which is
// exactly the case where directness is unknowable and must stay null.
func directRefs(bom *cdx.BOM) map[string]bool {
	if bom == nil || len(bom.Dependencies) == 0 {
		return nil
	}
	root := ""
	if bom.Metadata != nil && bom.Metadata.Component != nil {
		root = bom.Metadata.Component.BOMRef
	}
	if root == "" {
		return nil
	}
	for _, dep := range bom.Dependencies {
		if dep.Ref == root {
			set := make(map[string]bool, len(dep.DependsOn))
			for _, r := range dep.DependsOn {
				set[r] = true
			}
			return set
		}
	}
	return nil
}

// directness reports whether c is a direct dependency, or nil when unknown.
func directness(direct map[string]bool, c *cdx.Component) *bool {
	if direct == nil {
		return nil
	}
	v := direct[c.BOMRef] || (c.Purl != "" && direct[c.Purl])
	return &v
}

// diffVulns compares the vulnerability entries of two documents.
func diffVulns(from, to *cdx.BOM, sum *DiffSummary) []VulnChange {
	fromV := indexVulns(from)
	toV := indexVulns(to)
	var out []VulnChange

	ids := make([]string, 0, len(fromV)+len(toV))
	for id := range fromV {
		ids = append(ids, id)
	}
	for id := range toV {
		if _, seen := fromV[id]; !seen {
			ids = append(ids, id)
		}
	}
	sort.Strings(ids)

	for _, id := range ids {
		f, inFrom := fromV[id]
		t, inTo := toV[id]
		switch {
		case !inFrom && inTo:
			out = append(out, VulnChange{Kind: ChangeAdded, ID: id, Severity: topSeverity(t), Affects: affectRefs(t)})
			sum.VulnsAdded++
		case inFrom && !inTo:
			out = append(out, VulnChange{Kind: ChangeRemoved, ID: id, Severity: topSeverity(f), Affects: affectRefs(f)})
			sum.VulnsRemoved++
		}
	}
	return out
}

// indexVulns maps a document's vulnerabilities by id.
func indexVulns(bom *cdx.BOM) map[string]*cdx.Vulnerability {
	out := map[string]*cdx.Vulnerability{}
	if bom == nil {
		return out
	}
	for i := range bom.Vulnerabilities {
		v := &bom.Vulnerabilities[i]
		if v.ID == "" {
			continue
		}
		if _, dup := out[v.ID]; !dup {
			out[v.ID] = v
		}
	}
	return out
}

// severityRank orders CycloneDX severity labels, highest first.
var severityRank = map[string]int{
	"critical": 5, "high": 4, "medium": 3, "low": 2, "info": 1, "none": 0, "unknown": 0,
}

// topSeverity returns the highest severity label across an entry's ratings.
func topSeverity(v *cdx.Vulnerability) string {
	best, bestRank := "", -1
	for _, r := range v.Ratings {
		s := strings.ToLower(r.Severity)
		if s == "" {
			continue
		}
		if rank, ok := severityRank[s]; ok && rank > bestRank {
			best, bestRank = s, rank
		}
	}
	return best
}

// affectRefs lists the component refs a vulnerability entry points at.
func affectRefs(v *cdx.Vulnerability) []string {
	out := make([]string, 0, len(v.Affects))
	for _, a := range v.Affects {
		if a.Ref != "" {
			out = append(out, a.Ref)
		}
	}
	sort.Strings(out)
	return out
}

// diffGraph counts dependency edges added and removed.
//
// Edge counts rather than a listing: a graph change is usually the consequence
// of the component changes already listed above, and re-listing every edge
// would bury them. The counts are there so a diff that shows no component
// movement but a restructured graph — a dependency that became transitive —
// is still visible.
func diffGraph(from, to *cdx.BOM) (added, removed int) {
	fromEdges := edgeSet(from)
	toEdges := edgeSet(to)
	for e := range toEdges {
		if !fromEdges[e] {
			added++
		}
	}
	for e := range fromEdges {
		if !toEdges[e] {
			removed++
		}
	}
	return added, removed
}

// edgeSet flattens a dependency graph into a set of "ref→dep" strings.
func edgeSet(bom *cdx.BOM) map[string]bool {
	out := map[string]bool{}
	if bom == nil {
		return out
	}
	for _, d := range bom.Dependencies {
		for _, on := range d.DependsOn {
			out[d.Ref+"\x00"+on] = true
		}
	}
	return out
}

// preferName returns the first non-empty argument.
func preferName(vals ...string) string {
	for _, v := range vals {
		if v != "" {
			return v
		}
	}
	return ""
}

// changeKindOrder groups the change list by significance for display.
//
// Removals and downgrades lead because they are the changes most likely to be
// unintentional; additions and upgrades are the expected outcome of a
// dependency bump and read as noise above them.
var changeKindOrder = map[ChangeKind]int{
	ChangeRemoved: 0, ChangeDowngraded: 1, ChangeLicense: 2,
	ChangeVersionChanged: 3, ChangeUpgraded: 4, ChangeAdded: 5,
}

// sortChanges orders changes by kind, then name, in place.
func sortChanges(changes []ComponentChange) {
	sort.SliceStable(changes, func(i, j int) bool {
		a, b := changes[i], changes[j]
		if changeKindOrder[a.Kind] != changeKindOrder[b.Kind] {
			return changeKindOrder[a.Kind] < changeKindOrder[b.Kind]
		}
		if a.Name != b.Name {
			return a.Name < b.Name
		}
		return a.Purl < b.Purl
	})
}
