package binpkg

import (
	"archive/zip"
	"bytes"
	"compress/zlib"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

// TestFromBinaryReadsGoBuildInfo compiles a throwaway module and reads its
// dependency set back out of the binary — the case a container image presents
// when a Go service ships with no manifest beside it.
func TestFromBinaryReadsGoBuildInfo(t *testing.T) {
	goBin, err := exec.LookPath("go")
	if err != nil {
		t.Skip("go toolchain unavailable")
	}
	dir := t.TempDir()
	write := func(name, body string) {
		if err := os.WriteFile(filepath.Join(dir, name), []byte(body), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	write("go.mod", "module example.com/svc\n\ngo 1.24\n")
	write("main.go", "package main\n\nfunc main() {}\n")

	out := filepath.Join(dir, "svc")
	cmd := exec.Command(goBin, "build", "-o", out, ".")
	cmd.Dir = dir
	cmd.Env = append(os.Environ(), "GOFLAGS=", "GOWORK=off", "GOPROXY=off")
	if combined, err := cmd.CombinedOutput(); err != nil {
		t.Skipf("go build unavailable in this environment: %v: %s", err, combined)
	}

	res := FromBinary(out)
	if res.Format != "go" {
		t.Fatalf("Format = %q, want go", res.Format)
	}
	var sawStdlib, sawMain bool
	for _, p := range res.Packages {
		if p.Ecosystem != "golang" {
			t.Fatalf("unexpected ecosystem %q for %s", p.Ecosystem, p.Name)
		}
		if p.Method != MethodGoBuildInfo {
			t.Fatalf("Method = %q, want %q", p.Method, MethodGoBuildInfo)
		}
		switch p.Name {
		case "stdlib":
			sawStdlib = true
			if p.Version == "" {
				t.Fatal("stdlib package has no version")
			}
		case "example.com/svc":
			sawMain = true
		}
	}
	if !sawStdlib {
		t.Fatalf("expected the Go toolchain as stdlib, got %+v", res.Packages)
	}
	// A module built with no version stamped is skipped by design; a stamped one
	// must be marked direct.
	for _, p := range res.Packages {
		if p.Name == "example.com/svc" && !p.IsDirect {
			t.Fatal("main module must be marked direct")
		}
	}
	_ = sawMain
	if res.Attributes["go-main-module"] != "example.com/svc" {
		t.Fatalf("go-main-module attribute = %q", res.Attributes["go-main-module"])
	}
}

func TestGoToolchainVersion(t *testing.T) {
	cases := map[string]string{
		"go1.24.2":                      "1.24.2",
		"go1.25rc1":                     "1.25rc1",
		"devel go1.26-abc":              "",
		"":                              "",
		"go1.24.2 X:nocoverageredesign": "1.24.2",
		// GOEXPERIMENT suffixes are not part of the release version an advisory
		// database matches on.
		"go1.26.5-X:nodwarf5": "1.26.5",
		"go1.26":              "1.26",
		"gccgo (GCC) 14":      "",
	}
	for in, want := range cases {
		if got := goToolchainVersion(in); got != want {
			t.Errorf("goToolchainVersion(%q) = %q, want %q", in, got, want)
		}
	}
}

func TestFromJVMArchiveReadsPomPropertiesAndNestedLibs(t *testing.T) {
	dir := t.TempDir()

	// A nested library jar carrying its own Maven coordinates.
	var nested bytes.Buffer
	nw := zip.NewWriter(&nested)
	addEntry(t, nw, "META-INF/maven/org.example/inner/pom.properties",
		"groupId=org.example\nartifactId=inner\nversion=2.1.0\n")
	if err := nw.Close(); err != nil {
		t.Fatal(err)
	}

	outer := filepath.Join(dir, "app.jar")
	f, err := os.Create(outer)
	if err != nil {
		t.Fatal(err)
	}
	zw := zip.NewWriter(f)
	addEntry(t, zw, "META-INF/maven/com.acme/app/pom.properties",
		"#Generated by Maven\ngroupId=com.acme\nartifactId=app\nversion=1.0.0\n")
	addEntry(t, zw, "BOOT-INF/lib/inner-2.1.0.jar", nested.String())
	if err := zw.Close(); err != nil {
		t.Fatal(err)
	}
	if err := f.Close(); err != nil {
		t.Fatal(err)
	}

	res := FromJVMArchive(outer)
	if res.Format != "jvm" {
		t.Fatalf("Format = %q, want jvm", res.Format)
	}
	byName := map[string]Package{}
	for _, p := range res.Packages {
		byName[p.Name] = p
	}
	app, ok := byName["com.acme:app"]
	if !ok || app.Version != "1.0.0" || !app.IsDirect {
		t.Fatalf("outer coordinates wrong: %+v", byName)
	}
	inner, ok := byName["org.example:inner"]
	if !ok || inner.Version != "2.1.0" || inner.IsDirect {
		t.Fatalf("nested coordinates wrong: %+v", byName)
	}
	if len(res.Edges) != 1 || res.Edges[0].From != "com.acme:app@1.0.0" {
		t.Fatalf("expected one edge from the outer artefact, got %+v", res.Edges)
	}
}

func TestFromJVMArchiveFallsBackToManifestThenFilename(t *testing.T) {
	dir := t.TempDir()

	manifestJar := filepath.Join(dir, "mystery.jar")
	writeZip(t, manifestJar, map[string]string{
		"META-INF/MANIFEST.MF": "Manifest-Version: 1.0\r\nImplementation-Title: widgets\r\nImplementation-Version: 3.4.5\r\nImplementation-Vendor-Id: io.widgets\r\n",
	})
	res := FromJVMArchive(manifestJar)
	if len(res.Packages) != 1 || res.Packages[0].Name != "io.widgets:widgets" || res.Packages[0].Version != "3.4.5" {
		t.Fatalf("manifest fallback wrong: %+v", res.Packages)
	}

	nameJar := filepath.Join(dir, "commons-lang3-3.14.0.jar")
	writeZip(t, nameJar, map[string]string{"org/apache/Foo.class": "x"})
	res = FromJVMArchive(nameJar)
	if len(res.Packages) != 1 || res.Packages[0].Name != "commons-lang3" || res.Packages[0].Version != "3.14.0" {
		t.Fatalf("filename fallback wrong: %+v", res.Packages)
	}
}

func TestBuildOwnerIndexAttributesFilesToPackages(t *testing.T) {
	root := t.TempDir()
	mkdir := func(rel string) string {
		p := filepath.Join(root, filepath.FromSlash(rel))
		if err := os.MkdirAll(p, 0o755); err != nil {
			t.Fatal(err)
		}
		return p
	}
	writeFile := func(rel, body string) {
		p := filepath.Join(root, filepath.FromSlash(rel))
		if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(p, []byte(body), 0o644); err != nil {
			t.Fatal(err)
		}
	}

	// dpkg: file list plus the status file that carries the version.
	mkdir("var/lib/dpkg/info")
	writeFile("var/lib/dpkg/info/curl:amd64.list", "/.\n/usr\n/usr/bin\n/usr/bin/curl\n")
	writeFile("var/lib/dpkg/status", "Package: curl\nVersion: 8.5.0-2ubuntu10\nStatus: install ok installed\n\n")
	// apk: stateful F:/R: records.
	writeFile("lib/apk/db/installed", "P:busybox\nV:1.36.1-r29\nF:bin\nR:busybox\nR:sh\n\nP:musl\nV:1.2.5-r0\nF:lib\nR:libc.musl-x86_64.so.1\n")
	// pacman: %FILES% section with relative paths.
	writeFile("var/lib/pacman/local/openssl-3.2.1-1/files", "%FILES%\nusr/bin/openssl\nusr/lib/\n")

	idx := BuildOwnerIndex(root)
	if !HasFileOwnership(root) {
		t.Fatal("HasFileOwnership must be true when package databases exist")
	}

	cases := []struct {
		path, name, version, ecosystem string
	}{
		{"/usr/bin/curl", "curl", "8.5.0-2ubuntu10", "deb"},
		{"/bin/busybox", "busybox", "1.36.1-r29", "apk"},
		{"/lib/libc.musl-x86_64.so.1", "musl", "1.2.5-r0", "apk"},
		{"/usr/bin/openssl", "openssl", "3.2.1-1", "arch"},
	}
	for _, tc := range cases {
		owner, ok := idx[tc.path]
		if !ok {
			t.Fatalf("no owner for %s (index has %d entries)", tc.path, len(idx))
		}
		if owner.Name != tc.name || owner.Version != tc.version || owner.Ecosystem != tc.ecosystem {
			t.Fatalf("%s owner = %+v, want %s@%s (%s)", tc.path, owner, tc.name, tc.version, tc.ecosystem)
		}
	}
	if _, ok := idx["/usr/lib"]; ok {
		t.Fatal("pacman directory entries must not be indexed as files")
	}

	// Lookup translates a host path under the extracted root.
	hostPath := filepath.Join(root, filepath.FromSlash("usr/bin/curl"))
	if owner, ok := idx.Lookup(root, hostPath); !ok || owner.Name != "curl" {
		t.Fatalf("Lookup(%s) = %+v, %v", hostPath, owner, ok)
	}
	if _, ok := idx.Lookup(root, filepath.Join(root, "opt", "vendor", "agent")); ok {
		t.Fatal("unpackaged path must not resolve to an owner")
	}
	if HasFileOwnership(t.TempDir()) {
		t.Fatal("a plain directory has no package database")
	}
}

func TestDedupeKeepsFirstProvenance(t *testing.T) {
	got := Dedupe([]Package{
		{Name: "b", Version: "1", Ecosystem: "golang", Method: MethodGoBuildInfo, BinaryPath: "/x"},
		{Name: "b", Version: "1", Ecosystem: "golang", Method: MethodGoBuildInfo, BinaryPath: "/x", IsDirect: true},
		{Name: "a", Version: "2", Ecosystem: "cargo", Method: MethodCargoAuditable, BinaryPath: "/x"},
		{Name: "", Version: "3"},
	})
	if len(got) != 2 {
		t.Fatalf("Dedupe returned %d packages: %+v", len(got), got)
	}
	if got[0].Ecosystem != "cargo" || got[1].Name != "b" {
		t.Fatalf("unexpected order: %+v", got)
	}
	if !got[1].IsDirect {
		t.Fatal("direct-ness must be merged onto the kept entry")
	}
}

func TestLooksExecutableRecognisesFormats(t *testing.T) {
	dir := t.TempDir()
	cases := map[string]struct {
		body string
		want bool
	}{
		"elf":  {"\x7fELF\x02\x01", true},
		"pe":   {"MZ\x90\x00", true},
		"text": {"#!/bin/sh\necho hi\n", false},
		"tiny": {"MZ", false},
	}
	for name, tc := range cases {
		p := filepath.Join(dir, name)
		if err := os.WriteFile(p, []byte(tc.body), 0o755); err != nil {
			t.Fatal(err)
		}
		if got := LooksExecutable(p); got != tc.want {
			t.Errorf("LooksExecutable(%s) = %v, want %v", name, got, tc.want)
		}
	}
	jar := filepath.Join(dir, "x.jar")
	if err := os.WriteFile(jar, []byte("PK\x03\x04"), 0o644); err != nil {
		t.Fatal(err)
	}
	if !LooksExecutable(jar) {
		t.Error("jar extension must be recognised")
	}
}

func addEntry(t *testing.T, zw *zip.Writer, name, body string) {
	t.Helper()
	w, err := zw.Create(name)
	if err != nil {
		t.Fatal(err)
	}
	if _, err := w.Write([]byte(body)); err != nil {
		t.Fatal(err)
	}
}

func writeZip(t *testing.T, path string, entries map[string]string) {
	t.Helper()
	f, err := os.Create(path)
	if err != nil {
		t.Fatal(err)
	}
	zw := zip.NewWriter(f)
	for name, body := range entries {
		addEntry(t, zw, name, body)
	}
	if err := zw.Close(); err != nil {
		t.Fatal(err)
	}
	if err := f.Close(); err != nil {
		t.Fatal(err)
	}
}

// TestDecodeCargoAuditable covers the Rust path: the zlib-compressed crate list
// `cargo auditable` embeds in `.dep-v0`, including its build/runtime kinds and
// crate-level edges.
func TestDecodeCargoAuditable(t *testing.T) {
	payload := `{"packages":[
	  {"name":"app","version":"0.1.0","source":"local","kind":"runtime","root":true,"dependencies":[1,2]},
	  {"name":"serde","version":"1.0.203","source":"crates.io","kind":"runtime"},
	  {"name":"cc","version":"1.0.99","source":"crates.io","kind":"build"}
	]}`
	var buf bytes.Buffer
	zw := zlib.NewWriter(&buf)
	if _, err := zw.Write([]byte(payload)); err != nil {
		t.Fatal(err)
	}
	if err := zw.Close(); err != nil {
		t.Fatal(err)
	}

	res := Result{Attributes: map[string]string{}}
	decodeCargoAuditable(buf.Bytes(), "/usr/local/bin/app", &res)
	if len(res.Errors) != 0 {
		t.Fatalf("unexpected errors: %v", res.Errors)
	}
	if res.Format != "rust" {
		t.Fatalf("Format = %q, want rust", res.Format)
	}
	byName := map[string]Package{}
	for _, p := range res.Packages {
		if p.Ecosystem != "cargo" || p.Method != MethodCargoAuditable {
			t.Fatalf("wrong provenance: %+v", p)
		}
		byName[p.Name] = p
	}
	if app := byName["app"]; !app.IsDirect || app.Scope != ScopeProduction {
		t.Fatalf("root crate wrong: %+v", app)
	}
	if cc := byName["cc"]; cc.Scope != ScopeDevelopment {
		t.Fatalf("build-kind crate must be development scope: %+v", cc)
	}
	if serde := byName["serde"]; serde.IsDirect {
		t.Fatalf("non-root crate must not be direct: %+v", serde)
	}
	if len(res.Edges) != 1 || res.Edges[0].From != "app@0.1.0" || len(res.Edges[0].DependsOn) != 2 {
		t.Fatalf("edges = %+v", res.Edges)
	}
	if res.Attributes["cargo-auditable"] != "true" {
		t.Fatal("cargo-auditable attribute missing")
	}

	// Garbage in the section is reported, not fatal, and yields no packages.
	bad := Result{Attributes: map[string]string{}}
	decodeCargoAuditable([]byte("not zlib"), "/usr/local/bin/app", &bad)
	if len(bad.Errors) != 1 || len(bad.Packages) != 0 {
		t.Fatalf("bad section handling: errors=%v packages=%+v", bad.Errors, bad.Packages)
	}
}

// TestScanTreeAttributesAndAggregates walks a synthetic container root: a jar
// owned by no package, a jar the package database claims, and a text file that
// must be ignored.
func TestScanTreeAttributesAndAggregates(t *testing.T) {
	root := t.TempDir()
	mk := func(rel string) string {
		p := filepath.Join(root, filepath.FromSlash(rel))
		if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
			t.Fatal(err)
		}
		return p
	}
	writeZip(t, mk("opt/app/app.jar"), map[string]string{
		"META-INF/maven/com.acme/app/pom.properties": "groupId=com.acme\nartifactId=app\nversion=1.0.0\n",
	})
	writeZip(t, mk("usr/share/java/owned-1.2.3.jar"), map[string]string{"a/B.class": "x"})
	if err := os.WriteFile(mk("etc/motd"), []byte("hello"), 0o644); err != nil {
		t.Fatal(err)
	}
	// A pruned directory must not be walked.
	writeZip(t, mk("node_modules/dep/bundled.jar"), map[string]string{"c/D.class": "x"})

	owners := OwnerIndex{
		"/usr/share/java/owned-1.2.3.jar": {Name: "libowned-java", Version: "1.2.3-1", Ecosystem: "deb"},
	}
	res := ScanTree(TreeOptions{Root: root, Owners: owners})

	if res.Examined != 2 {
		t.Fatalf("Examined = %d, want 2 (node_modules pruned, text file skipped)", res.Examined)
	}
	names := map[string]bool{}
	for _, p := range res.Packages {
		names[p.Name+"@"+p.Version] = true
	}
	if !names["com.acme:app@1.0.0"] || !names["owned@1.2.3"] {
		t.Fatalf("packages = %+v", res.Packages)
	}
	if len(res.Unowned) != 1 || RelativePath(root, res.Unowned[0]) != "opt/app/app.jar" {
		t.Fatalf("Unowned = %v, want the unpackaged jar", res.Unowned)
	}
	var ownedArtifact *Artifact
	for i := range res.Artifacts {
		if strings.HasSuffix(res.Artifacts[i].Path, "owned-1.2.3.jar") {
			ownedArtifact = &res.Artifacts[i]
		}
	}
	if ownedArtifact == nil || ownedArtifact.Owner == nil || ownedArtifact.Owner.Name != "libowned-java" {
		t.Fatalf("ownership not attached: %+v", res.Artifacts)
	}
}

func TestMergeEdgesFoldsDuplicates(t *testing.T) {
	got := mergeEdges([]Edge{
		{From: "a@1", DependsOn: []string{"b@1", "c@1"}},
		{From: "a@1", DependsOn: []string{"c@1", "d@1"}},
		{From: "", DependsOn: []string{"x@1"}},
		{From: "e@1"},
	})
	if len(got) != 1 || got[0].From != "a@1" || len(got[0].DependsOn) != 3 {
		t.Fatalf("mergeEdges = %+v", got)
	}
}
