baseURL = "https://docs.cli.vulnetix.com/"
languageCode = "en-gb"
title = "Vulnetix CLI"

[markup.goldmark.renderer]
  unsafe = true

[markup.highlight]
  style       = "monokai"
  lineNos     = false
  codeFences  = true
  guessSyntax = true
  noClasses   = true

[params]
  description = "Automated vulnerability management CLI that focuses on remediation over discovery."
  images = ["https://www.vulnetix.com/images/og.png"]
